### ISSUE TITLE
missing texture reference when using gltf pack

### ISSUE THREAD

**Issue by anupamdas2012** [zeux/meshoptimizer#113]
Hi, for models that have textures, after I run gltf pack and attempt to load the model im getting missing texture reference errors
eg: gltfpack -i Sponza.gltf -o scenepacked.glb

from this dataset:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza/glTF

if I then try to view my packed .glb into something like the gltf viewer 
(https://gltf-viewer.donmccurdy.com/)

**I get this:**
IO_ERROR | Node Exception: TypeError: Failed to fetch | /images/0/uri
-- | -- | --
IO_ERROR | Node Exception: TypeError: Failed to fetch | /images/1/uri
IO_ERROR | Node Exception: TypeError: Failed to fetch | /images/2/uri
...etc

I've also tried using Babylonjs loader , and im getting missing texture errors.
If i try to pack a gltf that does not contain textures to begin with, everything works.

Please advice.

**Comment by zeux** [comment]
This works fine for me. Just to make sure - when you ask gltfpack to output a .glb file, by default the textures used by that file are still referenced using the original file paths, so you need to distribute the glb file *and* the original png/jpg images. If you want a self-contained .glb file, you need to use `-te` (stands for "embed textures") command line argument.

**Comment by zeux** [comment]
I'm going to assume the issue is missing -te; I've slightly tweaked the command-line help to emphasize that -te encodes textures into .bin/.glb, hopefully this will make it more clear.

gltf-pipeline has a different set of defaults and by default embeds textures into .glb as well, but I'm not sure this is good for download performance as it prevents downloading multiple textures in parallel, and makes the settings less orthogonal so I like the current approach better.
