### ISSUE TITLE
How to use binary fallbacks generated for EXT_meshopt_compression model?

### ISSUE THREAD

**Issue by karanganesan** [zeux/meshoptimizer#163]
Hi @zeux,

EXT_meshopt_compression is amazing, just wondering how the decoder handles the fallback binaries when EXT_meshopt_compression is not supported on a device or in a browser where web assembly support is not good/not working.

Does the decoder automatically use it or how can one handle it?

**Comment by zeux** [comment]
The assumption is that WebAssembly is supported by the browser.

If you need to support browsers without WebAssembly, it should be possible to, for example, generate files with fallback data (`-cf`) and conditionally register EXT_meshopt_compression plugin for three.js/Babylon.js. This isn't an officially supported path because to my knowledge all browsers except for IE11 support WebAssembly, and my understanding is that IE11 in general is a lot of trouble to support.

**Comment by zeux** [comment]
(worth noting is that there are other ways to support browsers without wasm, e.g. existing codec can be compiled into asm.js in theory by changing the build process a bit)
