### ISSUE TITLE
Provide gltfpack as a js module and also a cli tool.

### ISSUE THREAD

**Issue by lokiiarora** [zeux/meshoptimizer#164]
Can there be a module for gltfpack and also alongside the cli, using the https://docs.npmjs.com/files/package.json#bin .

Having a module would make easier for us folks here at [Scapic](https://scapic.com/) to integrate the same. We do have a very naive implementation right now.

Would love to know if this fits in your roadmap and would love to contribute if there is any help needed.

**Comment by zeux** [comment]
There's already a node.js based CLI (https://www.npmjs.com/package/gltfpack). As far as module is concerned, it's probably possible but I'm not sure what the best way is to do this - perhaps using Emscripten's virtual file system would make sense?

**Comment by lokiiarora** [comment]
Does the repository have a doc about the API surface of the WASM module?
If so, we can have two options:

1. Directly interfacing with wasm binary with some kind of type system
2. Having a library which interfaces the wasm and then the cli tool can use the same.

**Comment by zeux** [comment]
Right now gltfpack.js/wasm are built out of a C++ command-line application with no external API surface.
Indeed one way to go here is to build gltfpack.js/wasm as a library, and have a separate binary that's pure JS that calls into that, setting up access to real file system along the way.

What's the target execution environment for you right now - node.js or web?

**Comment by lokiiarora** [comment]
Node.js specifically, AWS Lambda.
I was not aware that you shipped with a binary cli as well !
On taking that and putting onto a layer, I end up getting logs like this:
![Error log](https://user-images.githubusercontent.com/20043762/87133871-90a7b300-c2b5-11ea-941f-303be5510316.png)
Error codde:
![Screenshot 2020-07-10 at 2 00 13 PM](https://user-images.githubusercontent.com/20043762/87133968-afa64500-c2b5-11ea-9c41-8ccc7eca5468.png)

**Comment by donmccurdy** [comment]
I'd be interested in picking up `EXT_meshopt_compression` in [glTF-Transform](https://gltf-transform.donmccurdy.com/) as well, and a JS API would certainly help with that. Or WASM is fine too, as long as it runs both in the browser and in Node.js. The tiny meshopt decoder is great, not sure if something similar is feasible for the encoder.

**Comment by lokiiarora** [comment]
I'd love to help as well @zeux !

**Comment by lokiiarora** [comment]
I'd love to help too @zeux  !
That way I'd get to know more about it too :)

**Comment by zeux** [comment]
@donmccurdy The encoding process is pretty different from the decoding process in that a lot of care needs to be taken to arrange the data properly; the interface to this can be quite complex, because of morph targets and the like. Because of this you *can* build an encoder out of individual C++ algorithms provided by meshoptimizer (which is what gltfpack does!), but it would be quite a bit of work to expose all of them through the JS interface, and then the resulting implementation would be reimplementing gltfpack... It's all doable, but I don't think I have the time or the motivation to do this :)

The module-like interface to gltfpack would be something else, just repackaging gltfpack to be runnable without a separate execution of node.js through a shell.

@lokiiarora I think I missed the earlier message, that's the native binary, right? Would be good to understand why it fails to run, I wonder if the system you're running this on doesn't have some shared libraries, e.g. version of glibc is different. Of course you can also run gltfpack.js through node.

**Comment by zeux** [comment]
P.S. As for modularization, I looked into this briefly and it doesn't look like it's possible to configure Emscripten's file system to be callback-based easily. As such one reasonable option would be to build a *separate* build of gltfpack.js as a library; I was hoping that the existing command line could be rewritten on top of that but I'm not sure how to do this with Emscripten's MEMFS which expects the caller to provide the necessary files ahead of time. I'll ask about this on Emscripten's repository.

**Comment by donmccurdy** [comment]
@zeux I see, thanks! That all makes sense, but I don't have any answers about Emscripten's MEMFS.

**Comment by zeux** [comment]
@lokiiarora Coming back to this after a long wait... I'm actually wondering, would a module interface that still used file names be useful to you? E.g. imagine you *had* to run in node.js context and work with file names, but you had an actual .js interface where you'd require gltfpack.js, and had an API to launch the packing process from some options? The filesystem route was a bit of a dead end but this might be a good compromise, at least something to start with.

**Comment by donmccurdy** [comment]
> ... a lot of care needs to be taken to arrange the data properly; the interface to this can be quite complex, because of morph targets and the like. 

In my case, I want to compress a mesh in isolation — gltfpack does a lot of helpful things, but if I need to cherry-pick a specific optimization without anything else changing, that is harder. One way I could imagine doing this in glTF-Transform would be to copy the target mesh into an empty glTF file and running gltfpack on it. I don't want to sacrifice the web browser compatibility in glTF-Transform, but could probably get creative about only including gltfpack when running in a CLI context.

**Comment by Inviz** [comment]
I would like to join in request of providing the api, so that gltfpack could be used in a more modular way. For me i wanted to de-opt of certain features (animation optimization), or work around of some missing features (like multiple scenes). But I created features requests for those anyways, so maybe my need isn't as acute anymore

**Comment by zeux** [comment]
@donmccurdy FWIW I'm currently exploring a new promising path which should make it so that gltfpack is usable as a JS library with ability to specify input & output files as JS buffers without any real file access, and without relying on node, with the command-line Node.js-only wrapper.

This would maintain the existing interface in spirit in that you'd still have to pass gltf data in & out, but presumably this would make it easier to plug gltfpack into glTF-Transform.

**Comment by donmccurdy** [comment]
Sounds really useful, thanks! Yes, I could work with that, basically copying a mesh or animation into a new glTF file temporarily so that gltfpack can run on it, before merging changes back into the original. Necessarily a bit slower than doing the changes in place, but seems like an acceptable tradeoff. Totally understand that the modularity is potentially pretty time-consuming to support. 👍
