### ISSUE TITLE
Vertex/index buffer compression compatibility?

### ISSUE THREAD

**Issue by linuxaged** [zeux/meshoptimizer#169]
which level of compatibility does meshoptimizer supply? Can something like encoding with version v0.14 but can't decode with v0.15 happen?

**Comment by zeux** [comment]
That's a good question, I'll add this information to README.

The compression formats are backwards-compatible between numbered releases. Data encoded with 0.13 can be decoded with all future versions, same for 0.14 vs (a yet unreleased) 0.15 etc.

Additionally, during encoding it's possible to specify a version of encoded data so that for example when upgrading to 0.15, the data can be encoded using a format that 0.14 can decode. This can be controlled using `meshopt_encodeVertexVersion` and `meshopt_encodeIndexVersion` (see documentation for these functions for details on argument range).
