### ISSUE TITLE
How to represent quantized vertex in shader?

### ISSUE THREAD

**Issue by linuxaged** [zeux/meshoptimizer#173]
i miss the point of how to use quantized vertex. should i de-quantize them or use the quantized vertex directly in vertext shader and how? a complete example will be really helpful!

**Comment by zeux** [comment]
You should use the quantized vertex in the vertex shader directly. I'm unsure what the environment you're working in is, e.g. three.js supports quantized vertex elements automatically without changing the shaders as long as the dequantization transform is incorporated into the shader.

**Comment by linuxaged** [comment]
i'm using the [Magnum](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1Attribute.html#a6c8c42c4e9b11dcac471cec52f6d237a). under the help of @mosra i have known how to deal with packed attributes. And found something interesting, when compression(meshopt_encodeVertexBuffer) is used there's no size difference between Vertex type
```
struct Vertex{
unsigned short x, y, z;
unsigned short nx, ny, nz;
};
```
and
```
struct Vertex{
unsigned short x, y, z;
unsigned int normal;
}
```

**Comment by zeux** [comment]
Ok - glad you were able to figure it out!

The compression results depend a bit on the source data and packing. For example:

- If the 32-bit normal is packed using 8_8_8_8, I'd expect it to still compress better than full 32-bit variant
- Unless the source normal just doesn't have enough precision in the first place
- If the 32-bit normal is packed using 10_10_10_2, these will be closer because the vertex codec is most effective at compressing byte-aligned components
- If the 32-bit normal is packed using octahedral 16_16, then I'd expect it to be a bit smaller than the other variant, but have more precision

So, "it depends" :)

**Comment by Ben-Mack** [comment]
> ... three.js supports quantized vertex elements automatically without changing the shaders as long as the dequantization transform is incorporated into the shader.

Does that mean the current implement of Three.js GLTFLoader + MeshOpt decoder already dequantizing in the shader?

**Comment by zeux** [comment]
Yes
