### ISSUE TITLE
Super-strict variation of `-kn` mode 

### ISSUE THREAD

**Issue by Inviz** [zeux/meshoptimizer#186]
Right now the file before and after `gltfpack`ing produces slightly different leaf hierarchy, even if all nodes are named. Right now it creates some semi-anonymous `mesh_***` meshes, inside named objects. The skinned meshes have slightly different hierarchy too. 

In general it's not a huge deal, but I wonder if it is at all techncially possible to retain the same hierarchy perfectly? In scenes that need manual manipulations with geometry, uvs, transformations, object substitutions it could be a source of issues. Ideally, the code working with optimized and unoptimized models could be exactly the same. Right now I have to make some allowances for it to work

**Comment by zeux** [comment]
The node hierarchy does need to change to support quantization - the only option without changing node hierarchy is to change node transforms, which doesn't work in some cases due to animations, and would actually break client-side node manipulation code.

Running in `-noq` mode (which naturally produces much larger files as it disables quantization) shouldn't add extra nodes. I *think* skinned meshes are supposed to be attached to their original node as well.

**Comment by Inviz** [comment]
I wonder if there could be some sort of a custom extra option that the clientside loader could use to bring things back to normal. Or i guess some sort of algorithm that I could use to clean up extra meshes and bring things back to what they were on load time.

**Comment by Inviz** [comment]
But I can recognize that maybe my use case is sort of unusual. But it's similar to "production"/"development" code environments. One would want to have "what you see is what you get" type of experience. So i do not insist on this strongly, and i could work around it in many ways. But it would be nice to handle some way.

**Comment by zeux** [comment]
So as I mentioned above, quantization requires this. It results in adding extra nodes for all meshes, and client application can of course "clean" this up, e.g. if it supports per-mesh transform (which glTF doesn't) it can remove the extra nodes. Since supporting quantization is impossible without adding extra nodes and -noq already can disable it, I'm going to close this since nothing else can really be done from that perspective. I have some thoughts about adding more options for quantization that allow for less aggressive quantization while still preserving the hierarchy, but that's separate from an option which guarantees hierarchy integrity which is not feasible.

**Comment by Inviz** [comment]
Thank you
