### ISSUE TITLE
meshopt_computeMeshletBounds meshopt_Meshlet parameter probably should be a reference

### ISSUE THREAD

**Issue by jamesdolan** [zeux/meshoptimizer#19]
meshopt_Meshlet is 636 bytes and is being passed by value. I am guessing this wasn't intended.

**Comment by zeux** [comment]
See https://github.com/zeux/meshoptimizer/pull/17 for some context - it can't be a reference because the interface for meshoptimizer is C, not C++; it was originally a pointer but then I reworked it to be a value since it simplified the calls. Out of curiosity, are you hitting any issues associated with that (warnings, etc.)? I'm up for changing that back to a pointer if there's a good reason, but I wasn't able to measure substantial overhead from the copy.

**Comment by jamesdolan** [comment]
No issue, just popped up in static analysis is all.
