### ISSUE TITLE
Binary Comparison in meshopt_generateVertexRemap fails because of padding bytes

### ISSUE THREAD

**Issue by hotslice** [zeux/meshoptimizer#193]
My Vertex struct is like so:
```
struct Vertex {
    glm::vec3 pos; // sizeof(glm::vec3) == 16
    glm::vec3 color; // sizeof(glm::vec3) == 16
    glm::vec2 texCoord; // sizeof(glm::vec2) == 8
    // invisible 8 bytes of padding
} // sizeof(Vertex) == 48
```

The binary comparison for 2 Vertexes with the same values for pos, color, and texCoord is still failing because the 8 padding bytes contain different garbage data, but are still being compared as part of hashUpdate4 which looks at the sizeof the entire struct.

I think it would be worth documenting in meshopt_generateVertexRemap comment that this behavior can occur, and for the user to explicitly zero those padding bytes. OR you could provide separate stride size and struct size parameters to avoid comparing those bytes at all.

edit: the parameter vertex_size and vertex_stride are already separate in VertexHasher, but vertex_size is passed for both from meshopt_generateVertexRemap. I was able to fix the issue by adding an overload with the vertex_stride parameter.

**Comment by hotslice** [comment]
Actually now I'm worried about sizeof(glm::vec3) being 16. I feel like it should be 12, which means there are 4 bytes of padding in between the vec3's also, which could theoretically also have random garbage. Maybe I should just memset the whole struct before use.

**Comment by hotslice** [comment]
But to memset 0 before setting any struct values I would lose my nice one liner to generate a new Vertex, which looks like this:
```
    vertexes.emplace_back(Vertex{a, color, {0, 0}});
```

It appears that other people have been aware of this problem before - padding isn't required to be initialized when you use initializer lists https://gustedt.wordpress.com/2012/10/24/c11-defects-initialization-of-padding/

A topic discussed in the comments is to use operator== for the struct instead of memcmp. In my code I define both operator== as well as a std::hash implementation for use with std::set and std::multiset. This was used to deduplicate vertices in a different place. But you have opted to instead use a custom hash based on binary representation. Do you think there would be a significant performance loss if I hacked up the code to just use std::set with my defined operators instead?

**Comment by zeux** [comment]
So this is definitely worth calling out in documentation. I'll look through the functions that use structural equality and add the relevant notes.

As you note, while it's possible to specify the stride separately, it doesn't fully solve the problem because padding may appear between the elements. In your case you could use `glm::packed_vecN` types to work around the issue.

Alternatively you can of course use std::unordered_set if you already are defining equality/hashing. This isn't a great addition to the library for a few reasons (C ABI & FFI concerns around callbacks, performance), but vertex remapping is one of the simpler algorithm the library provides so you should feel free to replace it with alternative implementations if it's inconvenient.
