### ISSUE TITLE
gltfpack: Improve handling of meshes with very large UV bounds

### ISSUE THREAD

**Issue by Momohanfeng** [zeux/meshoptimizer#194]
gltfpack version: 0.14 and 0.15

I convert my gltf model to gltfpack format by -tc, it will generate a new model correct. And then use KTX2Loader and GltfLoader to load the target model in Threejs(v0.122.0). 

But some textures are displayed as stretch(LEFT: before convert, RIGHT: after convert),  I don't know what's the reason for this result? what should I do to resolve it?
![IMG20201109_094430](https://user-images.githubusercontent.com/4652023/98491746-c7480700-2270-11eb-8d7c-c457a907f548.png)
![IMG20201109_095614](https://user-images.githubusercontent.com/4652023/98492234-3114e080-2272-11eb-922d-006a57993ec4.png)

**Comment by zeux** [comment]
Please attach a model that would allow me to reproduce this.

**Comment by Momohanfeng** [comment]
[test07.zip](https://github.com/zeux/meshoptimizer/files/5507781/test07.zip)
I put the model into the zip file in attachment, thank you

**Comment by zeux** [comment]
I looked into why this happens; this is due to some of the textures being mapped on geometry with very large UV range, e.g. one of the walls has a texture stretched because the ground mesh has some geometry that is mapped to the same texture with UV range min -376010.687500 0.709212 max 376014.500000 0.921277.

For now I'd recommend using `-noq` for this mesh. There are some changes planned to gltfpack that can improve the behavior for cases like these, so I'm relabeling this as "enhancement".

**Comment by Momohanfeng** [comment]
OK, thank you

**Comment by Inviz** [comment]
I have had similar issue that models from different sources had very different UV scale/vertex scale, affecting the quantization. I had to change source models to be in a similar range to fix this. I think if meshoptimizer could handle this in itself (e.g. by normalizing outlying values to the 90-percentile scale), this could be a non-issue.
