### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by shoupengwen** [zeux/meshoptimizer#196]
I'm sorry, I have a simple question. how to use it, i run it with one obj's file, but meshoptimizer just read and optimize it, not export it. so i am confused that i don't get a optimized file, i hope your answer. thank you

**Comment by zeux** [comment]
meshoptimizer is a library; as such, by itself it doesn't provide end-to-end optimization tools for .obj. Also .obj doesn't support GPU-ready formats, and part of the point of meshoptimizer is to optimize meshes for efficient rendering.

gltfpack (https://github.com/zeux/meshoptimizer/tree/master/gltf), which is developed as part of this repository as well, provides an end-to-end solution for mesh/scene optimization, and it can take .obj as an input - but it always produces .gltf files as the output, again because of the limitations of .obj format that make it impractical to output optimized meshes as .obj.

**Comment by shoupengwen** [comment]
well，thank you very much
