### ISSUE TITLE
Retain the names of the individual mesh within a node

### ISSUE THREAD

**Issue by kayesn786** [zeux/meshoptimizer#201]
Hi,

I have an application where I need to store the names of the meshes and change it with user actions.

I see the meshe names are like mesh_0, mesh_1...

I have tried -kn -noq but no luck

Is there any workaround for this?

Thanks

**Comment by zeux** [comment]
Right now mesh names are always removed, and the expectation is that node names are used to manipulate meshes. There's currently no option to change that, although the pending VRM change might fix this. Since the expectation in general is that you should be able to use node names to manipulate nodes, can you outline what your application does with the meshes?

**Comment by kayesn786** [comment]
Hi @zeux 
In my current implementation, am maintaining the names of each mesh and associating then with some buttons. so when the user clicks on the button, a mesh or a group of mesh is selected based on its name. and this highlights the face containing those meshes. 

I tried to keep the name in extra field and push it to each mesh.. but even that is removed
I really like the optimization that gltfpack does. It loads the model way faster and model is smooth without any loss of data. But it would be great if we could retain the names of individual mesh.

Thanks

**Comment by zeux** [comment]
I've looked into this a bit; it's possible to implement, but to make it predictable mesh merging will need to be disabled completely, which would need a new command-line flag.

I still don't understand the use case well here though. In glTF, a given node can have at most one mesh. Since gltfpack does preserve node names (esp. when using -kn), can't your application use node names instead of mesh names to implement the same interface?

**Comment by zeux** [comment]
I'm going to close this for now, as preserving mesh names in a way that has reasonable semantics for the user requires extra command line options and prevents merging which isn't great for compression, and based on the information I have today it still seems as if any code that relies on mesh names can be converted to instead rely on node names with no loss of functionality.

**Comment by vegarringdal** [comment]
@zeux 

Is it possible to keep the userData ?

![image](https://user-images.githubusercontent.com/2901416/108627660-12201000-7457-11eb-84fa-a6872a03730d.png)

We are trying to convert IFC files for some projects in to glTF files, and need some data to give a little useful information if user clicks on that element/mesh.

currently using:
`gltfpack -i somefile.glb -o newfile.glb -kn -km -ke -cc`
Se Im able to select same object, just misisng name/userData

Im kinda hoping this lib will be able to do miracle on loading time/memory usage.

**Comment by mtveerman** [comment]
@vegarringdal When using ifcconvert -> collada2gltf indeed the `userData.name` is filled with the IFC GlobalId. When using Gltfpack with the `-kn` option, the names are present on the Object3D level, instead of the Mesh level, as you expect. 

You need to traverse the ancestors (parents) of the Mesh, check if it's an Object3D and check if the name has a length of 22, which is the length of the IFC GlobalId. That way you will be able to find the object identifier.
