### ISSUE TITLE
gltfpack: Octahedral filter assert error

### ISSUE THREAD

**Issue by bin** [zeux/meshoptimizer#202]
I'm testing gltfpack on the [avocado sample gltf model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Avocado) using the command `gltfpack -tc -cc -kn -i avocado.gltf -o avocado.glb`.  However, the resulting glb contains a buffer with an octahedral filter but 406 vertices.  This causes `meshopt_decodeFilterOct()` to fail, as it expects the number of vertices to be a multiple of 4.  This issue also occurs when using just `gltfpack -tc -cc -kn -i avocado.gltf -o avocado.glb`.  It does not occur with just `-c` as opposed to `-cc`, since it doesn't apply filters with the former.

**Comment by zeux** [comment]
Yup, that's a problem. It went unnoticed thus far because the decoders that run in WebAssembly use a JS wrapper that pads vertices to 4 during decoding, but this doesn't work well when working with GLTF data in native code and doing decoding in-place...

The correct solution would be to re-use the existing scalar code as a tail fallback for all decoders and remove the %4 restrictions. I'm going to do this later this week; for now you could pad the data as well (and pass a rounded vertex count, e.g. `(count + 3) & ~3`), although that may require over-allocating the output buffer.
