### ISSUE TITLE
Issues with flat geometry in simplify

### ISSUE THREAD

**Issue by reduz** [zeux/meshoptimizer#206]
OK After a lot of testing, I am realizing that simplify has issues with flat geometry. I suppose the error is detected relative to the distance from the removed point to its new position, or something similar. In geometry with volume, this makes sense, but in flat geometry this appears to cause issues. Here is an example of such thing in a part of the Bistro from Crytek. 

https://user-images.githubusercontent.com/6265307/102661871-6f989780-415c-11eb-8968-d525358b9b0a.mp4

Attached also the geometry in gltf format
[casito.zip](https://github.com/zeux/meshoptimizer/files/5718066/casito.zip)

IMO the problem here is that the algorithm needs to properly consider also the distance from the point to the unconnected edges and use it as error.

![image](https://user-images.githubusercontent.com/6265307/102662926-9061ec80-415e-11eb-9eae-9780f3538c17.png)

**Comment by zeux** [comment]
That should already happen. Please upload the mesh you are testing on.

**Comment by zeux** [comment]
Hmm. I think this is actually the same as #86. The problem there is that some edge collapses result in triangle flips. In a model like this, what seems to be happening is that some vertices travel along paths that are *internal* to the model, and result in flipping some triangles, which results in odd visuals. The edge of the windows by itself is preserved, but it gets obscured by the flips:

![image](https://user-images.githubusercontent.com/1106629/102674031-65b96900-4149-11eb-8d42-e208f42e79b3.png)

![image](https://user-images.githubusercontent.com/1106629/102674039-6baf4a00-4149-11eb-9083-1e7d7bddc1eb.png)

I'm going to keep this open though because it has a very nice & simple model. I was planning to look into this issue anyway over the holiday break, but it's not a simple/one-line fix unfortunately. Stay tuned :)

**Comment by reduz** [comment]
Alright, thanks lots! Still, letting aside that the generated geometry seems incorrect, the error it reports is tiny in units, so these changes appear when very close to the camera. Should the error reported for this not be much bigger?

**Comment by zeux** [comment]
The issue is that the error for moving vertices that aren't on disconnected edges is wrt to the surface (which is flat), and the error for moving vertices that are on edges is wrt distance to the edge (which is correct for the silhouette).

E.g. here it looks like there's a vertex that travelled all the way from the middle of geometry to the corner of the wall, and if the wall didn't have any windows it would indeed result in zero visual error. The cause of the visual error here is in the overlap that the resulting triangle has due to the flip.

**Comment by reduz** [comment]
Ah I think I understand better, so the problem is that there is no overlap checking to see if an edge can be collapsed?

**Comment by fire** [comment]
I don't know if it helps to have more examples but I think this is the same bug.

https://sketchfab.com/3d-models/subd-minitutorial-8ee637a4afa44d95836749c994270dd3

![image](https://user-images.githubusercontent.com/32321/102691091-cb940800-41be-11eb-88cb-7b5b5a73c781.png)

**Comment by zeux** [comment]
Yeah that looks like the same problem. My only worry about this is that this extra restriction doesn't fit neatly into the current computational framework, and it's likely that introducing it is going to substantially slow the simplifier down (2x? we'll see). It's not a problem for Godot / general import, as it's very fast already, but it might be a problem for some other users that use the simplifier today for runtime mesh generation; however this is something that should be simple to make optional, as we need to extend the API for other reasons like #59 :) So it all fits together. I'm going to start working on this in the next day or two.
