### ISSUE TITLE
will directory js publish as a npm package ? just like gltfpack

### ISSUE THREAD

**Issue by deepkolos** [zeux/meshoptimizer#232]
npm package is more popular than source include, so please make an npm package to make this project more popular

**Comment by zeux** [comment]
I could definitely set things up to be able to publish `js/` folder as a standalone NPM package, e.g. `meshoptimizer`.

Out of curiosity, do you have a specific use in mind? I ask because the decompression code in `js/` has been integrated into Babylon.JS where the code is embedded into the distribution, and into Three.JS where the code is technically part of the examples but my understanding is that if you use GLTFLoader at all you'd need to copy it into the project or use smth like unpkg.com that can also be used to get meshopt_decoder.

**Comment by deepkolos** [comment]
thx for reminding, i don't know it has been integrated into three.js, i just read the gltfpack document and don't where to import the `js/meshopt_decoder.module.js` from three.js's package

maybe add some notes about what location to import from three.js or Babylon.JS

`three/examples/jsm/libs/meshopt_decoder.module.js`

**Comment by zeux** [comment]
> maybe add some notes about what location to import from three.js or Babylon.JS

That's a good point, I will add a note to that effect. FWIW an example was recently added to three.js that hopefully can show the usage, see https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_gltf_compressed.html
