### ISSUE TITLE
handling of KHR_materials_variants extension

### ISSUE THREAD

**Issue by issacclee** [zeux/meshoptimizer#233]
Hi Guys,
Currently, gltfpack seems to be striping away everything related to KHR_materials_variants when such extension presents in the input file. Is this behavior intended?If it is intended, are you guys considering adding support for KHR_materials_variants extension in the future? If so, maybe I can help

**Comment by zeux** [comment]
All extensions that aren't directly supported are stripped from the output since they just aren't loaded - it's unfortunately impossible to preserve them otherwise due to cross-referencing other elements of the scene (e.g. material variants extension refers to materials that are renumbered and processed).

To support this, we'd need to add support to https://github.com/jkuhlmann/cgltf/ which is used to parse the glTF files, and then add the relevant processing logic - instead of just having a single material pointer inside Mesh we'd need an extra `std::vector<cgltf_material*> variants` or thereabouts, and would need to augment existing code that just works with `.material` to also process variants. Plus the actual logic for writing this data out will need to be added of course.

**Comment by zeux** [comment]
I've submitted a cgltf PR for parsing support for this extension: https://github.com/jkuhlmann/cgltf/pull/132
Will look into gltfpack next.
