### ISSUE TITLE
gltf convert to glb => encounter mesh glitches issue

### ISSUE THREAD

**Issue by riveranb** [zeux/meshoptimizer#242]
Hi, I'm using gltfpack (fantastic tool) to convert/compress my gltf models.
When I try a model, I found the converted binary .glb file have vertices or triangle-indices issue (I'm not very sure).
I downloaded a ship model from free3d.com website (https://free3d.com/3d-model/wwii-ship-uk-king-george-v-class-battleship-v1--185381.html)
And uses blender to convert .obj file to become .gltf file. Then uses gltfpack to convert .gltf file to .glb file.
(command: gltfpack -i <input.gltf> -o <input.flb> [optional: -c | -cc]

Then I rendered that model using my 3d-display html with three.js .
Either compressed or unocmpressed .glb model file has some kind of glitch issue.

I am not sure if I had done something, so try to ask for help here.

original .gltf
![image](https://user-images.githubusercontent.com/7834765/108143226-48315d00-7102-11eb-93ca-5218a43b2727.png)

converted .glb
![image](https://user-images.githubusercontent.com/7834765/108143352-86c71780-7102-11eb-9d7b-2b5bf71a4e94.png)

**Comment by zeux** [comment]
Would you mind attaching the glTF file you got from Blender? I've used gltfpack to convert the .obj file directly to .glb and the result doesn't seem to have any issues:

![image](https://user-images.githubusercontent.com/1106629/108143961-8c2e4e80-707d-11eb-8a89-850d5a1bca2e.png)

**Comment by arpu** [comment]
wups @zeux how can we direct convert a .obj to .glb with gltfpack?

**Comment by zeux** [comment]
@arpu Just specify .obj as an input instead of .gltf/.glb.

**Comment by riveranb** [comment]
> Would you mind attaching the glTF file you got from Blender? I've used gltfpack to convert the .obj file directly to .glb and the result doesn't seem to have any issues:
> 

Yes you are right.
If I try to convert .obj to .glb/.gltf directly, everything is fine (rendered correctly) in my three.js web page.
Here is the .gltf model file (.zip) I used blender (v2.91) to export. If this can help..
https://drive.google.com/file/d/1cw_Ui7Rx6lw2bsm7Ey7uoHVwzj7-H2BU/view?usp=sharing

**Comment by zeux** [comment]
Ah, gotcha. This is a result of this issue: https://github.com/mrdoob/three.js/pull/18871

When you use .obj -> .glb conversion by gltfpack, the bump map is ignored since it can't be represented by glTF.
Your Blender converted scene attaches a bump map into the normal map slot. This results in incorrect shading in general, which is part of the reason for broken shading. The additional issue is that due to texture coordinate quantization, some triangles get a degenerate UV mapping where e.g. U coordinate on multiple vertices is exactly equal. This then causes the bug referenced above.

If you want to work around this bug, you can increase the number of bits gltfpack uses for texture coordinates by e.g. providing `-vt 14` as a command-line option (default is 12 which isn't quite sufficient for this model).

Ideally the issue in three.js would be fixed, as e.g. Babylon.JS doesn't suffer from the same issue and renders the model correctly, but I'm not sure if there are any plans to handle degenerate UVs more gracefully:

![image](https://user-images.githubusercontent.com/1106629/108306659-80b45380-7161-11eb-8389-84b611a5a7af.png)

**Comment by zeux** [comment]
P.S. It's also possible that you can fix this problem by getting the Blender export to output vertex tangent information, although I haven't checked this.

**Comment by zeux** [comment]
I’ve submitted a fix to three.js repository - starting with three.js r126 which should release in a couple of weeks the workarounds will not be necessary anymore.
