### ISSUE TITLE
After compressing the model, changing the texture does not display the pattern, only the color

### ISSUE THREAD

**Issue by xx0618** [zeux/meshoptimizer#245]
After compressing the model, when changing the texture, only the color is displayed without the texture pattern.
![52601](https://user-images.githubusercontent.com/71865768/109118158-ed40db00-777d-11eb-86dc-b5352cca33b7.png)

When it is not compressed, the texture pattern will be displayed normally.
![225152618](https://user-images.githubusercontent.com/71865768/109118188-f631ac80-777d-11eb-9552-1c8223e1dedf.png)

**Comment by zeux** [comment]
This is going to be hard to investigate without a model. Could you share the source model before compression, either publicly or privately via e-mail (see my profile)?

**Comment by xx0618** [comment]
The model has been sent to your mailbox, please check.

**Comment by zeux** [comment]
FWIW we've discussed this via e-mail; for posterity, the issue was that when changing a texture dynamically on a model that has been compressed with gltfpack, it's important to preserve the texture transform.

In three.js, this means that you need to preserve .repeat/.offset values, for example like this:

```
let replacement = texture.clone();
replacement.repeat.copy(material.map.repeat);
replacement.offset.copy(material.map.offset);
replacement.needsUpdate = true;

material.map = replacement;
material.needsUpdate = true;
```

... instead of simply changing the texture on a material without further tweaks. The same applies to full material replacement.

**Comment by xx0618** [comment]
Thank you very much for your help. I tried all the methods you mentioned, but still can't display the pattern. I wonder if there is a more effective method?

Evgeny

发件人: Arseny Kapoulkine<mailto:notifications@github.com>
发送时间: 2021年2月27日 6:46
收件人: zeux/meshoptimizer<mailto:meshoptimizer@noreply.github.com>
抄送: xx0618<mailto:xx0618@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [zeux/meshoptimizer] After compressing the model, changing the texture does not display the pattern, only the color (#245)


FWIW we've discussed this via e-mail; for posterity, the issue was that when changing a texture dynamically on a model that has been compressed with gltfpack, it's important to preserve the texture transform.

In three.js, this means that you need to preserve .repeat/.offset values, for example like this:

let replacement = texture.clone();

replacement.repeat.copy(material.map.repeat);

replacement.offset.copy(material.map.offset);

replacement.needsUpdate = true;



material.map = replacement;

material.needsUpdate = true;

... instead of simply changing the texture on a material without further tweaks. The same applies to full material replacement.

―

**Comment by zeux** [comment]
One other more straightforward way to perform texture substitution would be to use the new material variants feature that glTF supports through KHR_materials_variants extension.

gltfpack supports it as of latest master (you should be able to get a new executable on https://github.com/zeux/meshoptimizer/actions/runs/539694774).

To use this feature, you need to do two things:

a) Prepare the initial glTF asset (that feeds into gltfpack) with several material variants. You can do that with https://github.com/facebookincubator/glTFVariantMeld or with glTF-Transform (see https://github.com/donmccurdy/glTF-Transform/pull/172)
b) Use gltfpack to compress the asset as usual
c) Use a three.js extension to work with the variants at runtime, e.g. https://github.com/takahirox/three-gltf-extensions

I do want to note that the method I've provided above definitely does work. It might be a bit tricky because three.js is sometimes not fully intuitive, e.g. I spent a bit of time wrestling with the code above before realizing I needed to set `needsUpdate` booleans - but as long as you copy the transform values there's no real difference between compressed and uncompressed assets.
