### ISSUE TITLE
Model with instanced geometry breaks

### ISSUE THREAD

**Issue by MrMateo7** [zeux/meshoptimizer#254]
I have a model with a lot of instanced geometry, something like 300 instances of various base geometries.

Even with the most simple optimization `gltfpack -i [element] -o [element]` the geometry breaks.

This is how is supposed  to be (the trees are the instanced geometries)
![image](https://user-images.githubusercontent.com/80969412/111805725-4bee0600-889f-11eb-8f82-e5b5f0272b7b.png)

and this is what happen
![image](https://user-images.githubusercontent.com/80969412/111805993-85bf0c80-889f-11eb-83e9-b6404b227383.png)

Check the performance, also drops to 1fps always.

**Comment by zeux** [comment]
Some bugs with instanced geometry have been fixed in the last month or two. I would recommend checking if the latest build, which you can download from "Artifacts" section on this page https://github.com/zeux/meshoptimizer/actions/runs/539694774, works.

If it doesn't, please attach the level that reproduces this issue.

**Comment by MrMateo7** [comment]
@zeux this was already fixed?

Sorry I dont answer, but I dont uderstand what you mean with "the level that reproduces this issue", how I do that?

**Comment by zeux** [comment]
I don't know if this is fixed but as a rule of thumb I'm closing all issues that don't have activity for a while. If this still happens on the most recent build, you can upload the problematic scene as a GitHub attachment.
