### ISSUE TITLE
How to save optimized Mesh to obj/glb file？

### ISSUE THREAD

**Issue by chenxian9999** [zeux/meshoptimizer#26]
Great work！

Excuse me，
How to save optimized Mesh to obj/glb file？

**Comment by zeux** [comment]
There currently is no support for automatically saving optimized meshes since meshoptimizer doesn't provide a command line tool that can be used for optimizing files - it provides a set of functions and expects that they will be integrated into existing applications.

I have plans for GLTF oriented command line tool that will most likely be able to output glb.

**Comment by chenxian9999** [comment]
Thank you for the response.

look forward to your future work 👍 

Best regards,
chenxian
