### ISSUE TITLE
Align toktx usage with the latest release

### ISSUE THREAD

**Issue by arpu** [zeux/meshoptimizer#266]
found on gltf-transform git
https://github.com/donmccurdy/glTF-Transform/issues/215

**Comment by zeux** [comment]
I believe `assign_primaries` is mostly a technicality wrt the output image format descriptor (DFD) - unsure this would be very interesting to support - but `target_type` is indeed a great suggestion, as it allows higher quality decoding when using UASTC for single/dual channel textures. I will leave this open for a while though since this is only applicable for newest toktx release, and using these options with an older release would fail, so this requires version detection (which is cumbersome) or to simply wait for an official toktx release so that the command line interface stabilizes.

**Comment by zeux** [comment]
It looks like neither three.js nor Babylon.js actually implement target_type based selection either, so right now this change wouldn't actually change anything wrt quality or resulting size in practice. Because of versioning challenges I'm going to close this for now - we will come back to this when renderers start actually using this information, but I'd expect this to take a while and I'm trying to keep the issues that are open to things that definitely need doing.
