### ISSUE TITLE
Not keep mesh name/node names

### ISSUE THREAD

**Issue by MrMateo7** [zeux/meshoptimizer#267]
Hi!

I need to manipulate the meshes after load, getting by the mesh name, but even when `-kn` keep modifing the mesh names.
`gltfpack -kn -c -i ./obj/B03.glb -o ./obj/Botella.glb`

The names I need to receive (printed by model without gltfpack)
![image](https://user-images.githubusercontent.com/80969412/114209879-c05b1880-9924-11eb-90fe-76df3ee6a864.png)
The names I receive
![image](https://user-images.githubusercontent.com/80969412/114210235-25167300-9925-11eb-8445-7bd028ce571f.png)

What I'm doing wrong?

**Comment by MrMateo7** [comment]
Well, inspecting deep I found what is happening.
What gltfpack do is create an Object3D, assign it the name and extras data, and make de mesh children of that Object.
![image](https://user-images.githubusercontent.com/80969412/114231288-da562480-993f-11eb-9b1a-34660bb51fa3.png)
Is there any way of avoid this behaviour? I mean, respect the hierarchy.

**Comment by zeux** [comment]
There's no way to avoid inserting extra objects; this is necessary to specify the additional quantization transforms. Since you still *can* locate the notes by name, I'd recommend using the node name instead of the mesh name; unfortunately three.js somewhat conflates the two, but you can always look at the parent of the mesh object and run all the necessary logic that way.

**Comment by zeux** [comment]
See also https://github.com/zeux/meshoptimizer/discussions/244, https://github.com/zeux/meshoptimizer/issues/252, https://github.com/zeux/meshoptimizer/issues/201

**Comment by tiivik** [comment]
Impressive library! For what it's worth, + 1 from my side to be able to keep the hierarchy / mesh names.
This limits using meshoptimizer in my use case where consistency of mesh names is important.
