### ISSUE TITLE
gltfpack - Would it be possible to get the ability to specify -tu or -tc per texture index ?

### ISSUE THREAD

**Issue by br-matt** [zeux/meshoptimizer#273]
Hi, we would like to apply different levels of compression to individual textures. Would it be possible to add optional arguments to `-tu` and `-tc` specifying which index they should be applied to. 

Ex: `-tu 0,1 -tc 2` would apply `-tc` to material index 2 and `-tu` to 0 and 1

**Comment by zeux** [comment]
This is certainly possible in theory but the indexing seems rather fragile. I was thinking at some point to implement mode selection that varies by type (e.g. normalmaps use -tu) - any chance this maps to your use case better? IOW how are you planning to determine index values that you pass?

**Comment by br-matt** [comment]
Linking it to the GLTF descriptors would be great too, if we could say 'diffuseTexture' or 'occlusionTexture' etc.

We need to be able to address any texture in the GLTF arbitrarily. i.e. if we have a diffuse texture, an occlusion map, an emissive map etc. we want to be able to specify compression settings for each individually if we want to, rather than having general groupings.

**Comment by zeux** [comment]
Does that mean a type specific setting  isn’t sufficient? How will the settings be determined in that case for different textures of the same type?

**Comment by br-matt** [comment]
Hmm `-tu diffuseTexture,occlusionTexture,etc.. -tc emisiveTexture,normalTexture` would work as optional param. If you have some better idea, open to that too !

**Comment by zeux** [comment]
I was thinking about this and one downside to type-based selection is that there are lots of different texture types now due to the plethora of material extensions, and they keep being added. Full list at this point:

```
baseColorTexture
metallicRoughnessTexture
diffuseTexture
specularGlossinessTexture
clearcoatTexture
clearcoatRoughnessTexture
clearcoatNormalTexture
transmissionTexture
specularTexture
specularColorTexture
sheenColorTexture
sheenRoughnessTexture
thicknessTexture
normalTexture
occlusionTexture
emissiveTexture
```

That's a lot of different types and this list will keep growing - I'd like to keep the interface simpler so that it can be configured using "reasonable" defaults once. I'm wondering if it would be reasonable to, as a first cut, categorize this as:

- "color" - would apply to any texture that contains a color, such as baseColor, diffuse, specularColor, etc.
- "normal" - would apply to any texture that contains a normal, such as normal, clearcoatNormal
- "attribute" - would apply to any texture that contains attributes used in shading, e.g. metallicRoughness, transmission

This would dramatically simplify the usage, and maintain forward compatibility for future material extensions. This split specifically is also important because these texture classes have different color/data spaces - "color" is sRGB, "normal" is vectors encoded as RGB, "attribute" is linear. The differences between different compression formats are often more pronounced in one vs the other.

One other possibility is that if this split is too coarse, we could have two classes for "color" - maybe "baseColor" and "color", with the notion that "baseColor" may require higher precision as it's more obviously visible during shading, whereas other color textures (emissive, specularColor) don't always need the full precision. We could alternatively call "baseColor" "diffuse".

Please let me know if one of these would work.

**Comment by vBitreel** [comment]
I would personally take complexity and flexibility over keeping the interface simple, but reasonable defaults would make sense. I think 'color', 'normal' and 'attribute' classifications would work as a first stab, but it would be preferable to then have an override that works on top of this. E.g. I have a diffuseTexture, emissiveTexture and clearCoatTexture - perhaps I will want stronger compression for clearCoatTexture than the rest, because it's doing less work, so I'd be happy having a parameter that sets compression to apply for all 'color' textures, and then a separate override for clearCoatTexture.

**Comment by zeux** [comment]
Alright, given that right now there's no configuration options I will start with just the class-based differentiation and then we'll see based on specific examples that don't fit that well whether it's critical to have further configuration options and what the best option would be (e.g. it's possible that with this we would either not need anything else because all interesting examples where the tradeoff of quality/space is valuable are covered by this, or it's possible that if that is insufficient you actually need per-texture control to be able to say that a diffuse texture A needs UASTC quality 10 and a diffuse texture B actually just needs ETC1S quality 5). So I'm going to go ahead and implement the proposal above, and if we find that in many cases it's insufficient a different solution would be implemented on top.
