### ISSUE TITLE
gltfpack - Pass options to basis

### ISSUE THREAD

**Issue by dmnsgn** [zeux/meshoptimizer#277]
Is it possible to pass options to `basis` directly when using the `-tc` flag?

I am particularly interested in options like `uastc_level` or `comp_level` from Basis docs at [Command Line Compression Tool](https://github.com/BinomialLLC/basis_universal/blob/master/README.md#command-line-compression-tool), anything that can five a bit more control on the compression levels and quality.

Also probably related: could the `-ktx2` option be used as well instead of the (what I believe is) custom logic in https://github.com/zeux/meshoptimizer/blob/master/gltf/basistoktx.cpp#L158? I am not very familiar with the internals of gltfpack but it sounds like they share the same objective with the [basis encoder](https://github.com/BinomialLLC/basis_universal/blob/master/encoder/basisu_gpu_texture.cpp#L1304-L1305)?

Thanks!

**Comment by dmnsgn** [comment]
I see `-tq` groups `uastc_level` or `comp_level` into opinionated quality: https://github.com/zeux/meshoptimizer/blob/ad3d7e1d88e75f14669d3cb81e15f9abcf723dd4/gltf/image.cpp#L125

But I'd still be interested in `seperate_rg_to_color_alpha`, `mipmap`, `y_flip` etc

**Comment by zeux** [comment]
See #241 for y_flip. I don't think `seperate_rg_to_color_alpha` can be used in glTF unfortunately, since KTX2 subset that glTF specification supports doesn't allow swizzling. In general since gltfpack supports both basisu and toktx, it's unlikely that options that are specific to just one tool will be exposed.

As for `-ktx2`, this is a very recent flag in basisu. It will be supported in the future, but it didn't exist up until the release a month ago.

**Comment by dmnsgn** [comment]
Thanks for the clarification, it is outside the current scope of gltfpack.
