### ISSUE TITLE
Opitmized gltf has messed up animations

### ISSUE THREAD

**Issue by vujadin** [zeux/meshoptimizer#278]
After optimization with gltfpack some gltf files have messed up animation order. I'm attaching example file, optimize with gltfpack and try with first few animations to see the difference between non-optimized and optimized (animations with same name play different stuff).

[net_out.zip](https://github.com/zeux/meshoptimizer/files/6466415/net_out.zip)

**Comment by zeux** [comment]
Thanks! Something is wrong with the channel optimization, gltfpack is removing some of the animated tracks as it considers their impact insignificant, which is clearly wrong in this case. I'll take a closer look later.

**Comment by vujadin** [comment]
Any news on this?

**Comment by zeux** [comment]
Haven't had a chance to debug further, I'll take a look later this week.

**Comment by zeux** [comment]
I've debugged this just now. The issue here is that the net object has a scale of 200; gltfpack removes tracks that are near-constant and this determination is using a tolerance that is in local space, instead of world space, for translations. Since the scale on the root node is so large, the effective error is 200x of what gltfpack thinks it is.

It would be more correct to use world-space errors. I had a branch with this work shelved a while back, so I'm going to see if I can bring it back or if it's easier to fix this more tactically for now.
