### ISSUE TITLE
when load a glb error "file requires Draco mesh compression support"

### ISSUE THREAD

**Issue by Yes-Jumby** [zeux/meshoptimizer#286]
I wonder how could I add Draco mesh compression support to gltfpack?
is there anyone to give me a hand?

**Comment by zeux** [comment]
gltfpack doesn't support files that are encoded with Draco. If you want to reoptimize these, I'd recommend using a tool like `gltf-pipeline` to convert a glTF file with Draco to one without. Note that gltfpack provides its own algorithm for compression as well when using `-c` option.

**Comment by Yes-Jumby** [comment]
> gltfpack doesn't support files that are encoded with Draco. If you want to reoptimize these, I'd recommend using a tool like `gltf-pipeline` to convert a glTF file with Draco to one without. Note that gltfpack provides its own algorithm for compression as well when using `-c` option.

yes,i got what you means;but i wonder how could I add draco(C++) lib into gltfpack ,i think it will be more practical；

**Comment by zeux** [comment]
You can try to integrate Google's Draco library and decode the meshes during glTF parsing in parsegltf.cpp. I want to note though that this is a rare case where a change like this would *not* be accepted as a contribution, because gltfpack strives to have a minimal set of dependencies, and Draco alone takes much more time to build and results in a larger binary than the rest of gltfpack.

I'd also note that using Draco and recompressing with gltfpack later will results in a larger quantization error, because the error induced by Draco will be magnified by gltfpack. Because of this it's recommended to use gltfpack to process *source* glTF files, and the suggested gltf-pipeline step is just a workaround for cases when you don't have access to the version of the file before compression.
