### ISSUE TITLE
Is possible to set  certain vertex and face unchanged when simplify glb model?

### ISSUE THREAD

**Issue by Yes-Jumby** [zeux/meshoptimizer#295]
I have a 3D model,It is just a matrix(N*N),and I get all the vertex to triangle ，but i want to let certain vertex and face unchanged,here is the graph for comprehension
**plus:I could get all the vertex' index and all the face' vertex.**
![image](https://user-images.githubusercontent.com/51182133/119959966-10766300-bfd7-11eb-86a9-a7683517afed.png)

**Comment by zeux** [comment]
Just a note for the future - you can also use GitHub Discussions for questions, which helps me filter out bug reports more easily.

To answer this question, there's no way to lock the border in this way right now. It's planned as a future extension to the lower level simplification algorithm, but I don't see a good way to use it in gltfpack during glb simplification because the source file doesn't really contain the information to determine which specific vertices need to be locked.
