### ISSUE TITLE
Merge multiple GLTF files?

### ISSUE THREAD

**Issue by trusktr** [zeux/meshoptimizer#335]
Can gltfpack take multiple files and merge them into one?

**Comment by zeux** [comment]
This isn't currently possible.

I've been asked about this before and this is rather difficult to do because of how gltfpack implementation is structured. Briefly, gltfpack uses cgltf library and while parts of the data are read completely into gltfpack structures, where it would be trivial to merge them, parts of the data are read directly from cgltf tree, and supporting more than one input there would require invasive changes to a lot of code.

Merging two cgltf trees is also difficult because a lot of that code relies on interchangeability between pointers and indices, e.g. nodes refer to their children but these references are really pointing into a single node array -- this mirrors the glTF structure, but makes multiple trees fundamentally difficult to merge; you can think about this problem as merging two JSON glTF trees - merging by itself may be simple, but all indices break once you do so and fixing them up requires a lot of fragile code.

The good news is that https://github.com/donmccurdy/glTF-Transform has a "merge" command that should be able to produce a new glTF file that can then be fed as a single input to gltfpack.
