### ISSUE TITLE
An option to disable the animation resampling

### ISSUE THREAD

**Issue by lightwolf** [zeux/meshoptimizer#341]
When using hand crafted animations, resampling my produce unintended results (one example are animations baked into a stepped curve for clean loops).
An option to completely skip resampling would be extremely useful, either as "-af 0" or "-noa".

**Comment by zeux** [comment]
Thanks for the request. It makes sense but I'm interested in a few details because they would determine the implementation complexity for this feature.

- Would it be acceptable if this option didn't support animations that use cubic splines
- Would it be acceptable if this option assumed that different tracks in the same animation have a matching timeline (which is what would happen after baking), and either failed or resampled using one of the tracks, with possibly non-uniform time keys, otherwise.

Also, would it help at all if during resampling, the time key of the last frame was preserved exactly, so that e.g. resampling a 1.23 second long animation at 10 Hz would still produce frames every 100ms but the last two frames had timestamps of 1.2 and 1.23 seconds respectively (right now it would produce 1.2 and 1.3 or 1.2 alone I believe).

**Comment by lightwolf** [comment]
To be fair, I downloaded the source code and had a look at it - in my case the issue I had was solved by setting the interpolation of the exported animation curves to STEP.
I'll clean up my changes and submit a pull request.

Basically the reason for this are loops where an item moves from A to B and then needs to jump back to A at the start of a loop again. That jump is visible if the interpolation is anything but STEP.

On a side node, massive kudos for the project - I've seen a 100% performance increase with the assets I've created after running then through gltfpack.
