### ISSUE TITLE
UV Messed up

### ISSUE THREAD

**Issue by LorenzWieseke** [zeux/meshoptimizer#413]
My baked lightmap uses wrong uv after optimize
![image](https://user-images.githubusercontent.com/29607121/157217277-06c28e62-d0e0-423f-8e73-09b9682e0f1f.png)
![image](https://user-images.githubusercontent.com/29607121/157217319-7b451802-9c3b-4817-9917-6d5efa22b557.png)
[House_Test_Opt.zip](https://github.com/zeux/meshoptimizer/files/8204965/House_Test_Opt.zip)

**Comment by zeux** [comment]
I'm not sure which viewer you're using but it's likely a problem with your viewer:

- three.js based viewer (https://gltf-viewer.donmccurdy.com/) has broken UVs on both models
- Babylon.js based viewer (https://sandbox.babylonjs.com/) has correct UVs on both models

When using three.js, note that the standard material setup assumes that AO map uses UV1 and all other maps use UV0. Your model has the lightmap mapped to emissiveTexture instead of occlusionTexture, so the viewers can't display it; fixing the material setup results in correct rendering for three.js viewer, again before and other optimization.
