### ISSUE TITLE
Error: toktx is not present in PATH or TOKTX_PATH is not set

### ISSUE THREAD

**Issue by alisaad673** [zeux/meshoptimizer#417]
I am getting this error when i am trying to run the command
`gltfpack -i untitled.glb -cc -tc -o untitled_ktx.glb`

I have already installed the win64.exe one from https://github.com/KhronosGroup/KTX-Software/releases. But still getting the issue. Also tried changing the path in system settings to C:\Program Files\KTX-Software\bin\toktx.exe

![toktx](https://user-images.githubusercontent.com/35926530/159990355-c4dd0865-4d0b-477e-bab6-eb711cdf2a39.PNG)

**Comment by zeux** [comment]
It looks like you're running this from WSL? In this case the env variable needs to point to a Linux-recognizable path.

I'd also encourage using the new native binary you can grab from artifacts here https://github.com/zeux/meshoptimizer/actions/runs/1781975705 (it's pre-release, will be part of next release). This has integrated texture compression so that you don't need to worry about file paths or external tools.

**Comment by alisaad673** [comment]
Thank you for the help. It worked fine in windows terminal.
