### ISSUE TITLE
The hierarchy is not preserved when using -kn -noq

### ISSUE THREAD

**Issue by AhmadMansy** [zeux/meshoptimizer#424]
i am using glTFast plugin for Unity to load glb files and i when i try to use gltfpack to optimize the model, i found that i have to pass (-noq -kn) parameter to keep name (which is what i need). But the problem here that it moves the mesh to be a child of the node
this is the source model
<img width="242" alt="source" src="https://user-images.githubusercontent.com/54113248/165293971-bc146924-a0e0-493b-913b-d78d2ad4d3c7.png">

and this is the optimized one with gltfpack
<img width="273" alt="after gltfpack" src="https://user-images.githubusercontent.com/54113248/165294533-b89466c0-b33f-4155-ae7d-d40e17d84402.png">

So, how exactly can we preserve the hierarchy with both child-parent relation and names?

**Comment by zeux** [comment]
This is required by KHR_mesh_quantization extension as the extra node specifies the dequantization transform. The only way to preserve the hierarchy completely is to disable quantization via `-noq`.

**Comment by AhmadMansy** [comment]
thank your reply.
 Actually i also disable quantization because after that i use draco comoression using (gltf-transform).
so i use -noq -kn and still the issue here.

**Comment by zeux** [comment]
If you are passing `-noq` then you'd need to upload a glTF model that has its hierarchy changed when both options are passed.

**Comment by AhmadMansy** [comment]
sorry but i didn't get the last reply. Isn't it suppose for no quantization and keeping nodes to work together?
i mean that after using the tool i should have an optimized model but the heirarchy should be changed if i pass those two options

**Comment by zeux** [comment]
Yes, that's correct.

**Comment by AhmadMansy** [comment]
So this is a bug then, because this is not the case for any model i try with. at least in unity

**Comment by zeux** [comment]
Actually, sorry, I think the above is wrong. Looking at the code, I think gltfpack will always insert a new node for a mesh. This may be necessary in certain cases because glTF requires that there only be one mesh per node, and the processing pipeline may sometimes generate more than one mesh so it's done that way for simplicity. The quantization will indeed affect whether the extra node gets a transform but it doesn't affect whether the node is added at all - I think I remembered this incorrectly because three.js treats these a little differently, but from the glTF perspective there's indeed going to be an extra node.

**Comment by AhmadMansy** [comment]
Thank you for your fast response.
It's very sad that this great tool isn't support such a thing. I think i have to deal with it then inside unity.
But it would be great if there is a solution for that in the future.
Thanks

**Comment by jackbach** [comment]
I am on the same page with @AhmadMansy .
I would like to exchange optimised and non-optimised gltfs without further code changes. This would fit my dev workflow much better.

**Comment by zeux** [comment]
The core issue really here is that it's impossible to use quantization without changing the nodes. While gltfpack provides no-quantization mode, it's not as efficient and not the primary purpose of the tool. From this perspective really it's the case that applications need to adapt to a potentially changing node structure, since "optimized glTF" and "preserved node structure" are goals that fight each other.

The only possibility here is that gltfpack supports non-quantized mode in a special way where it takes extra care to not modify the hierarchy at all. I haven't looked yet into how easy it would be to reconcile with the existing path.

**Comment by AhmadMansy** [comment]
thank you
the last part of your reply is the key and is exactly what i am looking for.
I really appreciate your concern.
