### ISSUE TITLE
Keep `-te` option for .gltf.

### ISSUE THREAD

**Issue by fire** [zeux/meshoptimizer#459]
> Warning: -te is deprecated and will be removed in the future; gltfpack now automatically embeds textures into GLB files

The use case is I'm running gltf through https://cuelang.org/docs/ to parse for validation.

I have a step to convert a glb to a .gltf with embedded textures and gltfpack can do this. It's not worth invoking blender.

Hope this can be kept.

**Comment by zeux** [comment]
Could you clarify why you intend to convert to .gltf specifically, not .glb, and why you need the textures embedded?

**Comment by fire** [comment]
The original idea was to have the entire gltf as a single json document to parse, validate and store without going to the filesystem.

The Blender export and the gltf2 spec allows the somewhat cursed ability to store all .bins as base64 strings inside of a json.

I am using parsing tools that can use yaml, json and protocol buffers, so that's probably why the tooling wasn't as concerned about bloat.

The idea is to use https://cuelang.org/docs/about/ as a validation language with a varying schema that doesn't require recompiling gltfpack.

1. given a glb
2. pack using gltfpack to glb and optimized
3. expand the glb as a gltf json document for reporting and validation purposes
4. save glb or reject it

```bash
# This is some of the tool output.
# This uses Blender export as embedded json.
bytes: 162852
Warning: -te is deprecated and will be removed in the future; gltfpack now automatically embeds textures into GLB files
{
    "scenes": 1,
    "nodes": 27,
    "materials": 1,
    "images": 1
}
{ width: 1024, height: 1024 }
mesh_0_primitive_0_index_count: 1728
mesh_0_primitive_0_triangle_count_if_trimesh: 576.0
```

**Comment by zeux** [comment]
Okay - I roughly understand this but I don't fully understand how this is related to `-te` :)

gltfpack doesn't know how to encode resources as data URIs - it never had support for this, it never outputs files with data URIs even if inputs used them, and data URIs are soft-deprecated from what I can tell (https://github.com/KhronosGroup/glTF/issues/1915)

gltfpack currently has two output modes:
- output file is a .glb - the result is a single file, all geometry and texture data is stored in the embedded buffer inside GLB
- output file is a .gltf - the result is multiple files, the glTF data is stored in file.gltf, the geometry data is stored in file.bin, the texture data is either stored in separate files (if the source asset used separate files), or added to file.bin (if the source asset embedded textures into buffers/URIs)

At some point before, whether the texture data was stored in the buffer or in separate files was controlled by `-te` setting - this was confusing to pretty much everyone involved as it resulted in saving multiple files when targeting .glb without separate options. Thus the option was removed in favor of the simpler behavior above - the option right now does *nothing*, the warning is just there for people who used to use it. Note that even with that option, the .gltf output path always produced two files, .gltf and .bin.

For your case, it seems like there are two possibilities:

1. Use gltfpack to export .gltf file, and use that .gltf file for validation ignoring any external resources. This implies that validation doesn't need access to the geometry/texture data, which may or may not be true.
2. Use the flow you've sketched, with step 3 performed by some other tool - it should be straightforward to do that without deep dependencies on glTF internals, since GLB files produced by gltfpack only have a single buffer specification, you just need to extract JSON and binary chunk, find the "buffer" node in the JSON chunk, and add a "uri" attribute to it containing the binary chunk contents.

Either option should work without using deprecated `-te`, and neither option would work better if `-te` was actually implemented from what I can tell.

**Comment by fire** [comment]
Thanks for the analysis. I'll attempt to implement 2 since the external data like images are important to check for mime type and texture width and height.

One appraoch would be take the glb, and split into { json: "...", buffer: ["...", "..."] } CUE document.

**Comment by zeux** [comment]
Sounds good. One other potential option in the future is to add more information to gltfpack report (`-r`); the information that exists there can be used to validate the "complexity" of assets, however it currently doesn't provide detailed breakdown of image information (eg maximum texture dimensions / used mime types).

**Comment by fire** [comment]
To be clear, you'll accept a pr for the complexity of assets as json? I'm not sure what format the report is in.

**Comment by zeux** [comment]
It's already JSON:

```
zeux@zeux-desktop:~/meshoptimizer$ ./gltfpack -i data/sketchfab/junkrat/scene.gltf -o jrat.glb -r /dev/tty
{
	"generator": "gltfpack 0.18",
	"scene": {
		"nodeCount": 77,
		"meshCount": 4,
		"materialCount": 4,
		"textureCount": 12,
		"animationCount": 1
	},
	"render": {
		"drawCount": 4,
		"instanceCount": 4,
		"triangleCount": 37451
	},
	"data": {
		"json": 33715,
		"binary": 34568724,
		"buffers": {
			"vertex": 693308,
			"index": 224706,
			"animation": 54944,
			"transform": 3968,
			"image": 33591777
		}
	}
}
```
