### ISSUE TITLE
gltfpack: mesh.primitives merged unexpectly

### ISSUE THREAD

**Issue by scarletsky** [zeux/meshoptimizer#470]
I am using [this build](https://github.com/zeux/meshoptimizer/actions/runs/2897189450) of gltfpack.

The origin model is here [monkey.glb.zip](https://github.com/zeux/meshoptimizer/files/9400220/monkey.glb.zip)

![image](https://user-images.githubusercontent.com/2386165/186096601-1a9694d8-63a3-47ef-86e4-4a6faf751243.png)

No matter what flags (`-kn -km -ke -vpf -noq`) I pass, gltfpack will merge the primitives unexpectly.

![image](https://user-images.githubusercontent.com/2386165/186097430-1abe2b30-c30d-453c-86bc-cfe17ba7b07a.png)

**Comment by zeux** [comment]
This is by design - the point of gltfpack is that it reorganizes and reprocesses the scene to make it more efficient. The options you quoted affect various aspects of transformations that have an impact on application access - eg without `kn`, an application that uses named node access may not get access to the node or meshes attached to it. However, primitives are an internal detail of glTF file encoding and as such they don't get a special option to block merging.

**Comment by scarletsky** [comment]
The original glb above is output by my own gltf exporter, it omitted all materials fields.

And I've output another glb by blender. At this time the `mesh.primitives` had `material` field:
![image](https://user-images.githubusercontent.com/2386165/186301102-1d74115c-019d-4d02-9fda-14d70117da50.png)

I use the same `gltfpack -kn -km -ke -vpf` command, and the `mesh.primitives` are not merged.
![image](https://user-images.githubusercontent.com/2386165/186301523-d0aa3018-4331-4df4-abfa-7450c36a8be2.png)

So if I want to keep the original primitives, I need to assign different material to them, right ?
