### ISSUE TITLE
Some metrics

### ISSUE THREAD

**Issue by elect86** [zeux/meshoptimizer#5]
Hi Arseny,

first of all, awesome project, really cool.

Second, sorry if I opened an issue, but this is something more like a request for any info regarding some performance metrics.

I'm developing a jvm port of Assimp [here](https://github.com/kotlin-graphics/assimp) and I should implement some state-of-the-art post-process techniques to improve the time required to render them. 

Before ending up on your repo, I was actually looking for the best method to improve vertex caching.
And I guess it's this one: ["An Improved Vertex Caching Scheme for 3D Mesh Rendering"](https://pdfs.semanticscholar.org/51ac/016d6c6afebace22f6f82b3d09e930ca0d55.pdf). Because it's even better than Amd Tootle by a 10% (although it requires ~100x time)

Anyway, as I already said, I'd be interested to know if you have ever taken any metrics about your mesh optimizer. Or if you have some considerations/feedbacks between implementing simply a lone vertex caching optimization and a full-pipeline optimization like your project.

Thanks in advance

**Comment by zeux** [comment]
The demo project outputs ACMR & ATVR metrics (e.g. see log here: https://travis-ci.org/zeux/meshoptimizer/jobs/374261973), which is what you need I suppose.

AMD Tootle uses the same algorithm as CacheFifo in the output above (meshopt_optimizeVertexCacheFifo). It's worth noting that while it runs faster than meshopt_optimizeVertexCache, and while it can generate results that are close on a HW with a fixed-size FIFO cache, most hardware doesn't use a cache that behaves like that. Because of this, the recommended algorithm is meshopt_optimizeVertexCache - this is an implementation of Linear-Speed Vertex Cache Optimisation by Tom Forsyth, that has been further tuned for running performance and for output efficiency on real hardware.

I've experimented with K-Cache before (from the paper you linked); I believe the results were a much higher runtime, as you note, and efficiency on par with current meshopt_optimizeVertexCache algorithm. I'm fuzzy on the details, and unfortunately I don't have the implementation anymore since I abandoned it for being impractical.

**Comment by Xottab-DUTY** [comment]
@zeux, could you say what is ACMR and ATVR? Google tries to foist A**S**MR and ACM Research instead of A**C**MR and gives me [this](https://en.wikipedia.org/wiki/ÁTVR) instead of ATVR.
![thonking64](https://user-images.githubusercontent.com/2989212/47955071-5e0fc800-dfb4-11e8-9a83-c680e1172bb7.png)

**Comment by zeux** [comment]
ACMR = Average Cache Miss Ratio
ATVR = Average Transform to Vertex Ratio

Both metrics are explained here http://www.realtimerendering.com/blog/acmr-and-atvr/

**Comment by Xottab-DUTY** [comment]
Thank you!

I wanted to say that it would be great if this information would be addeв in readme.. But it's already in it.. Sorry :D
