### ISSUE TITLE
Normals artifacting after meshopt compression using gltfpack and gltftransform

### ISSUE THREAD

**Issue by kitaedesigns** [zeux/meshoptimizer#515]
After applying Meshopt compression the first 5 and last 5 frames of a morph target animation create shading artifacts on face normals. All other animation frames seems to be unaffected. Tested with latest release of gltfpack and with gltf.report which uses gltftransform under the hood. I can provide link to model download for testing as well but have tested with multiple models that all use morph target animation.

![AC1084CF-1612-438E-A7EF-210470F7D4D2](https://user-images.githubusercontent.com/23407511/203589294-cffd4967-b996-4e5d-94c1-0ee3dbfeb81d.jpeg)

**Comment by zeux** [comment]
This is probably due to quantization; extreme normal deformations may result in morph normal deltas outside of [-1, 1] range. An example file would be appreciated.

**Comment by zeux** [comment]
Closing since I can't reproduce this without an example.

**Comment by kitaedesigns** [comment]
Ah sorry, I missed this, i can send you an example of this occurring.

Best,

Kitae Kim

Third Axis
www.thirdaxis.io<http://www.thirdaxis.io>



________________________________

**Comment by kitaedesigns** [comment]
https://app.box.com/s/9m8hrpuflghqgws090d9h8f5rqh6axuy

Best,

Kitae Kim

________________________________

**Comment by zeux** [comment]
Could you also share the version of this model before applying compression?

**Comment by kitaedesigns** [comment]
Sure!
https://app.box.com/s/wbjk82aqt65m0rcs5klos2rleppdo59u

Best,

Kitae Kim

**Comment by zeux** [comment]
I think I'm going to close this because it actually looks like more or less a problem with glTF-Transform and not as much with gltfpack.

Here's the model transformed with `gltf-transform quantize` (shown in Babylon.JS sandbox without diffuse texture):

![Screenshot 2023-09-26 at 1 16 07 PM](https://github.com/zeux/meshoptimizer/assets/1106629/8494ed3d-e0dc-4988-9622-3e914e8cf3cf)

Here's the model transformed with `gltfpack`:

![Screenshot 2023-09-26 at 1 19 37 PM](https://github.com/zeux/meshoptimizer/assets/1106629/40fd383c-86ed-46ac-bb28-d65c16831e8d)

I tried to capture the gltfpack screenshot to highlight that there are indeed some normal deformations but they are barely visible with diffuse texture.

Now, the fundamental problem here is not really solveable - the morph normal deltas have a worst case range `[-2, 2]`, and the normalized quantized range is `[-1, 1]` for signed integers. I think the difference is that gltf-transform doesn't clamp the deltas to `[-1, 1]` range before quantizing so you get integer overflow even if the value is slightly outside of `[-1, 1]` range, which really distorts the results.

Because the gltfpack artifacts look fairly minor, I think realistically clamping works well enough here. If a better solution is desired, a compressor may decide to just leave the normal deltas unquantized if a large percentage of them are well outside the `[-1, 1]` range. I'm not sure there's a clean solution otherwise.
