### ISSUE TITLE
sortPointMesh increases result size.

### ISSUE THREAD

**Issue by insar-dev** [zeux/meshoptimizer#528]
I found that sortPointMesh fun increased the result size.
![image](https://user-images.githubusercontent.com/1676595/212239513-60a78e97-5b5c-4bfc-b3aa-b77b69da39e6.png)
[0-original.rar.zip](https://github.com/zeux/meshoptimizer/files/10408262/0-original.rar.zip)

**Comment by insar-dev** [comment]
para:   -i 0-original.glb -o 0-compress-nosort.glb -c

**Comment by zeux** [comment]
This is due to the fact that point cloud sorting assumes spatial locality is good, but here the size is dominated by the extra ID attributes, and sorting by position is breaking up the ID order, resulting in a larger cumulative size even though the position attribute gets smaller due to sorting.

As an aside, the ID attributes aren't processed properly - the fact that they are parsed is accidental as gltfpack currently doesn't handle custom attributes...

**Comment by insar-dev** [comment]
@zeux thanks for your reply. I come here from the Cesium.
Cesium suggests using  EXT_meshopt_compression to compress point cloud.
The Cesium uses EXT_mesh_features to store ID attribute or other attributes.

![image](https://user-images.githubusercontent.com/1676595/213607844-24290209-fd4e-44b2-9e60-930b4e39bf7b.png)
https://cesium.com/blog/2021/11/10/introducing-3d-tiles-next/

Will the meshoptimizer support custom attributes?
And I find it also not supports Cesium's extension.
After running gltfpack, the extension is gone...
![image](https://user-images.githubusercontent.com/1676595/213608344-dc7e2ae3-46e9-4014-b4a9-07ebf206d3a1.png)

**Comment by zeux** [comment]
> Will the meshoptimizer support custom attributes?
> And I find it also not supports Cesium's extension.
> After running gltfpack, the extension is gone...

Note that all of these are questions about gltfpack - EXT_meshopt_compression is a glTF extension that doesn't necessarily require gltfpack to compress. Presumably Cesium-specific utilities can produce fully compressed 3D Tiles Next files - gltfpack currently doesn't support 3D Tiles.
