### ISSUE TITLE
gltfpack: EXT_texture_webp support

### ISSUE THREAD

**Issue by kzhsw** [zeux/meshoptimizer#536]
Spec [here](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_texture_webp).

Model before:
[webp_demo.zip](https://github.com/zeux/meshoptimizer/files/10695236/webp_demo.zip)
```json
{
"textures":[{"sampler":0,"extensions":{"EXT_texture_webp":{"source":0}}}],
"extensionsUsed":["EXT_texture_webp"],"extensionsRequired":["EXT_texture_webp"]
}
```
Model after:
[webp_demo_gltfpack.zip](https://github.com/zeux/meshoptimizer/files/10695237/webp_demo_gltfpack.zip)
```json
{
"extensionsUsed":["KHR_mesh_quantization","KHR_texture_transform"],"extensionsRequired":["KHR_mesh_quantization"],
"textures":[{}]
}
```

**Comment by kzhsw** [comment]
A similar thing is the proposal of [EXT_texture_avif](https://github.com/KhronosGroup/glTF/pull/2235).

**Comment by zeux** [comment]
This requires https://github.com/jkuhlmann/cgltf/issues/248; I'm not very interested in implementing this myself and gltfpack can't encode webp images without external dependencies anyway so the best it can do here is to preserve inputs as is, but if the linked issue gets implemented I can take a look at this.

Keeping unknown extensions doesn't work because image files need to be parsed for material transparency optimization.
