### ISSUE TITLE
gltfpack removes existing KHR_textures_basisu extension

### ISSUE THREAD

**Issue by prollin** [zeux/meshoptimizer#537]
Running `gltfpack` on a file already using the `KHR_textures_basisu` extension removes all traces of the extension in the output file

**Comment by zeux** [comment]
This is not a bug and rather a current limitation - you can pass `-tc` to recompress source textures if they are present. If `KHR_texture_basisu` is a required extension, gltfpack currently will refuse to process the file, because it assumes the role of a tool that converts a "vanilla" glTF file (that doesn't use various compression extensions) to an optimized one (that might).

**Comment by prollin** [comment]
For context, our use case was to use `gltf-transform` (or custom tool) for compression since it gave us a bit more flexibility there and `gltfpack` for geometry.

**Comment by zeux** [comment]
Got it, thanks. Out of curiosity, what prevents you from using gltfpack to compress the textures as well?

**Comment by prollin** [comment]
`gltf-transform` offers more granularity and more options for texture processing; we want to be able to resize certain class of textures and also have a bit more control over compression parameters.
