### ISSUE TITLE
Export the UV data into the glb file even though there are not textures

### ISSUE THREAD

**Issue by VikasB1904** [zeux/meshoptimizer#543]
I am using the gltfpack utility to get compressed glb file.
The original glb file has the UV data even though it does not contain any texture.
After the compression using the gltfpack, UV data gets removed from the compressed glb file.
As a result I can not apply texture on this glb file by loading it in the Three.js based applications.
So can you keep the UV data as it is in the input file or do you know a way to fulfill my requirement.
I have attached the files you can refer.
[cube_.zip](https://github.com/zeux/meshoptimizer/files/10898682/cube_.zip)

**Comment by zeux** [comment]
This isn't really feasible for somewhat fundamental reasons: for quantization to work, KHR_texture_transform needs to be used, and it can't be applied with no texture bindings. Replacing the textures with three.js sort of requires gltfpack to write this info somewhere.

This is not a problem without quantization, but that's a secondary mode that's not really how the tool is designed to be used.

My recommendation would be to make sure the files use some texture, so that it can be replaced at runtime.

**Comment by VikasB1904** [comment]
@zeux Is there any way/workaround through which I can retain my UVs from the input glb file.
I tried with -noq option to avoid the texture optimization, but it did not worked.

regards

**Comment by fy0** [comment]
> This isn't really feasible for somewhat fundamental reasons: for quantization to work, KHR_texture_transform needs to be used, and it can't be applied with no texture bindings. Replacing the textures with three.js sort of requires gltfpack to write this info somewhere.

try " -kn -km -ke -noq"

And I support the suggestion, UVs is useful

**Comment by CITIZENDOT** [comment]
Applying a very small texture (like 1x1 png) retains the UV data. You can change the material after loading the model, runtime.
