### ISSUE TITLE
gltfpack: No output on a large obj input

### ISSUE THREAD

**Issue by kvark** [zeux/meshoptimizer#545]
My invocation:
```bash
"C:\Program Files\gltfpack.exe" -i tmp\fostral.obj -o tmp\fostral.gltf -si 0.125
```
Waits for about 30 seconds, then exits. The output file is not created.
The size of "fostral.obj" is about 5 Gb. It has 165M vertices and 74M quad faces.
Doing the same on a smaller model (500 Mb) worked fine.

I'll need to run this through a debugger, but figured an issue is needed regardless.

Using release-0.18 on Windows-11.

**Comment by zeux** [comment]
This is probably an out-of-memory crash, although it's difficult to know which exact step crashed without debugging. There were a few iterations of reducing memory usage for huge models but probably more work can be done on this...

**Comment by zeux** [comment]
The most likely cause for this is out of memory during simplification; `meshopt_simplify` requires ~236 bytes per vertex during the algorithm execution, plus gltfpack would consume ~48 bytes per vertex for actual vertex data assuming the mesh has positions, normals and texture coordinates, and ~24 bytes per vertex for index data, which on this level would add up to ~308 bytes/vertex => ~50 GB RAM requirements - unless the system has ~64 GB RAM I'd expect this to OOM.

For meshopt_simplify, required memory per vertex consists of 44 bytes for error quadrics, 12 bytes for internal positions, 17 bytes for various connectivity structures, 56 bytes for edge adjacency structure, 72 bytes for collapse list, 24 bytes for collapse order, 5 bytes for other collapse tracking data, ~6 bytes for temporary position remap.

Some of this memory is overallocated for the worst possible case, notably collapse list+order consumes ~40% of memory here and is usually overallocated ~2x (20% waste), but it's not a guarantee that less memory would suffice under all circumstances. Most other data is allocated out of necessity, so I'd say that even with a substantial amount of work, cutting more than 100 bytes/vertex (=> 16GB out of 50 GB) is unlikely to be possible.

The memory requirements for `meshopt_simplifySloppy` which is used in gltfpack as a fallback are much less steep and scale better with requested resulting resolution, at expense of simplification quality. Because this is used as a fallback, gltfpack would need a new option that effectively asks it to use `meshopt_simplifySloppy` exclusively. Alternatively, it's possible to simplify the mesh by cutting it in a few pieces, simplifying each piece, merging the results and then simplifying the result again if necessary. With 8:1 simplification ratio this could get memory requirements down 5+x. Alternatively-alternatively, if the .obj file is pre-cut into multiple mesh groups, the problem might be that gltfpack is too eager to merge these during .obj parsing. That is easy to fix but it will not help if the mesh has only one face/material group.

Considering that I don't have any models in my test set over 6M vertices, I don't think I can work on any of this right now :) I'll take a look at collapse list management and a couple other items in the list above at some point but this is orthogonal to the issue at hand as, as noted, even if `meshopt_simplify` was ~optimal this mesh - assuming it's one giant mesh - would still OOM.

Let me know if you can share the file in question. Otherwise this is probably too vague by itself to be actionable.

**Comment by kvark** [comment]
Thanks for looking into this!
I [uploaded the file](https://drive.google.com/file/d/1K3Yxa9EuuvcG3HgADPTVIhC-gZ5zAXWB/view?usp=sharing) to google drive, in case you want to give it a shot.

**Comment by zeux** [comment]
Okay thanks! The good news is that this file is *not* as challenging as I was worried :sweat_smile: 

The crash actually happens due to a bug in fast_obj library. I'll fix this shortly. After fixing this, the command you ran works just fine and takes "only" 20 GB or thereabouts. The reason for the mismatch between this and my projections above is that even before simplification, gltfpack reduces the number of vertices from 165M to 79M by merging equivalent vertices together (which is lossless). This reduces the memory requirements accordingly for the subsequent simplification pass, and since mesh only has positions, it takes ~16b + ~236b + ~24b per vertex => ~20 GB.
