### ISSUE TITLE
gltfpack: M1 version of macbook is not supported

### ISSUE THREAD

**Issue by vannvan** [zeux/meshoptimizer#547]
Can provide a running program that supports the Macbook M1 version？

**Comment by zeux** [comment]
The macOS release binary (https://github.com/zeux/meshoptimizer/releases/tag/v0.18) should run fine on M1. Due to a current packaging limitation you'll need to mark the binary as executable (chmod a+x) but that's about it.

The binary will run through Rosetta, so it wouldn't be as fast as it could possibly be. Fixing this requires GitHub support for M1 hardware I believe, which I'm hoping will happen soon...

**Comment by vannvan** [comment]
> The macOS release binary (https://github.com/zeux/meshoptimizer/releases/tag/v0.18) should run fine on M1. Due to a current packaging limitation you'll need to mark the binary as executable (chmod a+x) but that's about it.
> 
> The binary will run through Rosetta, so it wouldn't be as fast as it could possibly be. Fixing this requires GitHub support for M1 hardware I believe, which I'm hoping will happen soon...

I understand the correct usage, thank you
