### ISSUE TITLE
Need PointCloud deduplicate after quantization?

### ISSUE THREAD

**Issue by a8301592** [zeux/meshoptimizer#579]
I understand quantizization is about use intergers to replace float , it will lose some accuracy,it will make some different point to be togerther.
So, I think  PointCloud do depulicate when data had quantized and before invoke meshopt_encodeVertexBuffer.

**Comment by zeux** [comment]
In theory this is true. This hasn't been done mostly because normally you'd want quantization levels to be selected such that the points do *not* get merged too much - if you have a very dense point cloud you should probably use `-si` parameter to explicitly ask to simplify it - and post-quantization merging is currently a little difficult to integrate into gltfpack due to how the code is written.

**Comment by a8301592** [comment]
get it ,i will try simplify later.
