### ISSUE TITLE
Output of gltfpack can't be used with unreal 5.2

### ISSUE THREAD

**Issue by jerobarraco** [zeux/meshoptimizer#584]
i'm using goxel to generate some gltf files that i've been importing to ue 5 for some time. using vertex colors.
but when i run gltfpack on them, the result can't be imported.
i tried gltf and glb and the same error. even tried with each one of the flags and get always the same. 

![image](https://github.com/zeux/meshoptimizer/assets/3729895/e69d0425-b631-411c-9681-119d11fd3a10)

the files
[Files.zip](https://github.com/zeux/meshoptimizer/files/12114682/Files.zip)

**Comment by zeux** [comment]
You can verify that the result of gltfpack is a valid glTF file here: https://github.khronos.org/glTF-Validator/. The tool reports 0 errors and warnings on the attached file.

By default gltfpack uses `KHR_mesh_quantization` extension. You can try using `-noq` flag in case UE5 glTF importer doesn't support this extension.

In any case, since the file is valid glTF file, this is either a bug or a missing extension support in UE5.2 glTF importer. I recommend filing a bug for this to Epic.
