### ISSUE TITLE
Add simplify option to gltfpack

### ISSUE THREAD

**Issue by FreakTheMighty** [zeux/meshoptimizer#60]
Thank you for this super useful library! I would like to further optimize models by running simplification. It would be really helpful if `gltfpack` allowed me to do this one shot.

For example, `-si 0.4` could reduce the poly count to 40% of the original.

` ./gltfpack -i glTF-Sample-Models/2.0/BarramundiFish/glTF/BarramundiFish.gltf  -o ./glTF/BarramundiFish-simple.gltf -si 0.4`

**Comment by zeux** [comment]
Yeah that's a good idea. The command line specifics are somewhat nuanced as there's some complexity with automatically reducing the entire scene to a given polygon target in a "safe" (appearance-preserving) way, will probably start with something simple. Also since gltfpack now supports point cloud data will need to consider that as well - the library currently doesn't have point cloud simplification support.

**Comment by FreakTheMighty** [comment]
I’m not super familiar with gltf pack. Maybe it’s worth making a separate cli, like gltfreduce, to prevent feature creep in gltfpack.

**Comment by zeux** [comment]
Nah, integrating this into gltfpack is perfectly reasonable, I'm just not sure yet what the exact set/behavior of the command line options should be.
