### ISSUE TITLE
gltfpack: Keeping external textures in .glb

### ISSUE THREAD

**Issue by petrbroz** [zeux/meshoptimizer#605]
When optimizing gltfs with `gltfpack`, is it somehow possible to keep textures external, i.e., not bundle them into the output glbs? And if not, would it be possible to add a flag for this? I believe this would be really helpful when `gltfpack` is used for optimizing gltf/glb content of individual tiles in a 3D Tiles dataset where many tiles might be sharing the same textures.

**Comment by zeux** [comment]
That currently happens automatically when the output is .gltf (not .glb).

**Comment by petrbroz** [comment]
Thanks @zeux. Do you think it would make sense to make this kind of behavior available for glbs as well? I understand that the main purpose of glbs is to have everything bundled in one file but for the 3D Tiles use case I mentioned above, keeping the textures separate even for glbs might be useful IMHO.

**Comment by zeux** [comment]
It’s certainly easy to add an option, but I’d like to make sure it’s useful. For 3D tiles, are both gltf and glb supported? Is gltf worse in some way?

Quick background: gltfpack used to default to separate textures regardless of the format and provided an option, -te, to embed textures into .bin (gltf) / .glb. This was very error prone when producing glb as separate textures there are very rare and the general expectation is that glbs are self contained. As such it was removed in favor of format dependent behavior. Rationale is more fully described here: https://github.com/zeux/meshoptimizer/issues/178

In practical terms, I haven’t measured it in a while but my expectations were that for geometry heavy data with textures stored separately, storing geometry separately is beneficial because it allows the loaders to parse glTF file and then concurrently download geometry and textures.

**Comment by zeux** [comment]
By the way, in your use case, are textures being compressed or left as they are in the source file? If they were compressed, where would you want gltfpack to put them? I'm trying to come up with behavior that would simultaneously fix a few different issues so having more specifics about this use case would be great.

**Comment by petrbroz** [comment]
Thanks for looking into this! Our models aren't texture heavy so we don't compress them.

**Comment by wallabyway** [comment]
We take a large single GLTF, and split it up into smaller GLB files, spatially.
However, these GLB's share a common texture.  This is where it makes sense to use ext-reference texture folder.

You can see how we modified glTFPack CLI for our purpose here:
https://github.com/zeux/meshoptimizer/compare/master...petrbroz:meshoptimizer:master

It seems to work, but it would be so much better to have actual support within your official gltfpack tool.

**Comment by petrbroz** [comment]
Thank you @zeux! Looking forward to the next release with the `-tr` flag :+1:
