### ISSUE TITLE
gltfpack: Wrong text position after optimization

### ISSUE THREAD

**Issue by benjaminzaufall** [zeux/meshoptimizer#615]
After using gltfpack, the position of the text in a gltf model isn't right anymore

Here is one example:
![image](https://github.com/zeux/meshoptimizer/assets/1440521/bc6cce03-8417-4d53-b222-f5bc9fdcac88)

And here is the original model, before using gltfpack
[model.zip](https://github.com/zeux/meshoptimizer/files/12841646/model.zip)
(it's an animation, you can see it after some seconds, when the text appears)

I tried several flags, but nothing worked.

**Comment by benjaminzaufall** [comment]
It would be very nice, if there is a workaround or something - I have to put this in production by the end of the week :-)

**Comment by zeux** [comment]
What version are you using? On the attached model, using master build, I see no difference before/after gltfpack:

- Before gltfpack (attached file):
![image](https://github.com/zeux/meshoptimizer/assets/1106629/ef381632-4251-45f5-a2c2-71f1a18f0326)

- After gltfpack (no extra arguments):
![image](https://github.com/zeux/meshoptimizer/assets/1106629/d3c858da-5635-44b8-8f2b-a6c28c817033)

**Comment by benjaminzaufall** [comment]
oh sorry, very stupid - that was the wrong file. now the right one:
[model_right.zip](https://github.com/zeux/meshoptimizer/files/12841652/model_right.zip)

I'm using 0.19, the newest version

Wait untill "Simulation" appears

**Comment by benjaminzaufall** [comment]
"Simulacrum" seems to work, the issue only appears with "Simulation"... Both models have this issue, the first one also, but it's displayed later in the animation

**Comment by zeux** [comment]
Thanks - I see the issue now. Looks like gltfpack is getting confused wrt translation animation: as the scale of the node gets adjusted, it seems to think the translation is unimportant because it evaluates it in context of the initial node scale (which is almost 0 but not exactly 0).

Minor note (probably unrelated) - looks like the source here is transformed with glTF-Transform with enabled quantization; I'd recommend disabling quantization since gltfpack will do it itself and the result will be a little higher quality with that enabled.

But to be clear this is a bug, so it'll need to be fixed. It doesn't look like any existing options affect this so this requires a code change; the only way to work around this without the code change is to change the initial scene to make sure that the scale of the text nodes is *exactly* 0 (right now it's very small but very close to 0, notably this affects `polySurface66` and `polySurface67` nodes).

**Comment by benjaminzaufall** [comment]
okay i understand that - glad, I could found this issued and help to improve the project.
just one question: is it possible to run gltfpack only for texture compression and no other actions are getting processed?

**Comment by zeux** [comment]
No - there's no way right now to only use gltfpack for texture compression.

The issue has been fixed in master just now, the updated binary builds are available here: https://github.com/zeux/meshoptimizer/actions/runs/6450083005 (under Artifacts)
