### ISSUE TITLE
Documentation direction Encoder User Guide

### ISSUE THREAD

**Issue by RyugaRyuzaki** [zeux/meshoptimizer#666]
This library is amazing. However, it would help everyone if the author could create user manuals for each feature. for an example:
- THREE.Group has children [mesh1, mesh2, ...etc]
- const glb = (await exporter.parseAsync(Group , opts)) as ArrayBuffer;
The question is how we can use MeshoptEncoder for this?

**Comment by zeux** [comment]
js APIs are documented here: https://github.com/zeux/meshoptimizer/blob/master/js/README.md

MeshoptEncoder in particular is designed for use by projects like gltf-transform; Decoder is already integrated into three’s gltf loader.

**Comment by zeux** [comment]
So just to clarify, the expected flow is that you use gltfpack or glTF-Transform to encode (the latter uses JS version of meshoptimizer), and if you use THREE's glTF loader to load the file (which has meshopt decoder integrated with examples available in THREE's repository), things will just work. The JS library is meant for processing tools and loaders, as the README linked above indicates.

If further questions arsie I would recommend using Discussions instead of Issues.

**Comment by RyugaRyuzaki** [comment]
> So just to clarify, the expected flow is that you use gltfpack or glTF-Transform to encode (the latter uses JS version of meshoptimizer), and if you use THREE's glTF loader to load the file (which has meshopt decoder integrated with examples available in THREE's repository), things will just work. The JS library is meant for processing tools and loaders, as the README linked above indicates.
> 
> If further questions arsie I would recommend using Discussions instead of Issues.

I'm really sorry, i will move it to Discussion
