### ISSUE TITLE
Simplification produces non manifold edges

### ISSUE THREAD

**Issue by roenyroeny** [zeux/meshoptimizer#699]
Might be related to https://github.com/zeux/meshoptimizer/issues/698 / https://github.com/zeux/meshoptimizer/issues/346

Simplifying this mesh procures output with 1 non manifold edge ( edge with more than 2 faces )

input wireframe:
![image](https://github.com/zeux/meshoptimizer/assets/13182141/6493722f-58b2-48fd-9c6a-67d811a08210)

output wireframe:
![image](https://github.com/zeux/meshoptimizer/assets/13182141/78ebc7ac-26e4-4794-80e9-564372e6e435)

This edge is non manifold: Meshlab has a handy view for this.
![image](https://github.com/zeux/meshoptimizer/assets/13182141/9e1489bb-44c6-4f61-b9d9-c9a8cc3ec636)

(fixed) [repro.zip](https://github.com/zeux/meshoptimizer/files/15496189/repro.zip) containing the input mesh and code to reproduce.

repro case it should output
```
duplicate face found 102 104
```

**Comment by zeux** [comment]
Are you sure you attached the correct input mesh? I had to change main.cpp to open input.obj instead of test.obj, but after doing that I do not get the "duplicate face" output using latest master like this:

g++ main.cpp ../src/simplifier.cpp -I../src -DTRACE=0 && ./a.out

(note, had to also add includes math.h, string.h, and change void main to int main for code to compile)

**Comment by roenyroeny** [comment]
My bad. I think i attached the wrong one. Will update asap!

**Comment by roenyroeny** [comment]
Sorry about that. i accidentally attached the obj from the other issue.
I've reuploaded the repro in the first post and added the missing includes. i used MSVC which magically provides these.

Thanks for looking into this, much appreciated!

**Comment by zeux** [comment]
Attaching a minimal repro for completeness (24 input triangles, 10 output triangles):

[repro-minimal.zip](https://github.com/user-attachments/files/15757219/repro-minimal.zip)

**Comment by zeux** [comment]
Yeah, thinking about this more there should just not be an assumption that the output of simplification is manifold; the edge collapse algorithms usually don't guarantee this, and I don't think topological analysis here is warranted.

Note that in this case, the creation of the edge can be viewed as a subset of #346 - the last two collapses shown on the image (the ones that directly create the two-sided triangle) both result in a ~82 degree rotation. A more aggressive threshold would prevent the collapses shown above. However, this is probably separate from the topological restrictions - a reasonable assumption should probably be that non-manifold edges may appear in the output, but improvements to flipping logic would solve this specific case.

**Comment by RikoOphorst** [comment]
@zeux Extremely impressive debugging work, that's a seriously difficult problem! If you have the time for it, could you share some light on how you build these step by step visualizations of this problem?

**Comment by zeux** [comment]
I wish there was a trick to this :sweat_smile: I'm using a combination of Blender (in this specific case it helps that Blender's builtin visualization of vertex indices, which is enabled via "developer extras" in interface settings, displays indices that are aligned with .obj file when exporting only positional data), small tracing additions to simplifier.cpp that I will submit later to make detailed debugging like this easier in the future (via TRACE macro), and just hand annotating things based on this data with iPad / pencil.

It helped that I was able to reduce this test input iteratively to be manageable by changing the repro source code to brute force search every possible target index count (as the problem is dependent on the specific collapse set which varies a little depending on target index count, and you need to make sure the problematic edge doesn't get collapsed after being created), and just manually removing geometry while the problem persisted.

![image](https://github.com/zeux/meshoptimizer/assets/1106629/6f08006f-e3a2-4323-859e-956dab274401)

**Comment by RikoOphorst** [comment]
@zeux That's impressive! Figured the workflow would be something along the lines of this. I really should get more comfortable with tools like Blender to make all this less painful to debug - that tidbit on the vertex indices visualization is very useful. Thanks for sharing!
