### ISSUE TITLE
Add support for EXT_mesh_feature extension

### ISSUE THREAD

**Issue by wallabyway** [zeux/meshoptimizer#732]
glTFpack already supports custom vertices, including _feature0, and compresses them. However, it currently excludes the EXT_mesh_feature extension, which causes it to be (correctly) ignored by some viewers.

To quickly test support for meshOpt with the EXT_mesh_feature extension, I made a small modification to add the extension back:

```
           ...
	    {"EXT_mesh_gpu_instancing", ext_instancing, true},
	    {"EXT_mesh_features", true, true},
	};
```

I added the above lines to this section of code:
[meshoptimizer/gltf/gltfpack.cpp#L842](https://github.com/zeux/meshoptimizer/blob/30fe9fed38f963fb8bb9a255e8eb27fafc5b4746/gltf/gltfpack.cpp#L842)

After making the change, I compiled the project:
```
cmake . -DMESHOPT_BUILD_GLTFPACK=ON -DMESHOPT_BASISU_PATH=basis_universal -DCMAKE_BUILD_TYPE=Release
cmake --build . --target gltfpack --config Release
```

I then ran the modified gltfpack on a sample 0.glTF file containing FeatureID’s. The output was a GLB file that included the `EXT_mesh_features` extension header and the FeatureID’s in the custom vertices _feature0 buffer:

[0.glb.zip](https://github.com/user-attachments/files/16422453/0.glb.zip)

https://github.com/zeux/meshoptimizer/issues/573#issuecomment-2257478532

**Comment by wallabyway** [comment]
Argh, you are absolutely right.  I'm so sorry.

I spoke with Cesium folks about this.  The missing parameters (see below)...

```
"meshes" : [ 
"primitives"：［｛
   "extensions" : {
     "EXT_mesh_features" : {
        "featurelds" : [
          "featureCount" : 4,
          "attribute" : 0
```
![image](https://github.com/user-attachments/assets/3773ff9f-37e1-49d5-a0e7-a21446f23e29)

.. help with multiple feature sets (which is a bit overkill for my use-case, but that's ok, I'll talk with cesium folks on addressing this in the spec).

You make a good point, that in order to support this, I'll need to modify the gltfpack code and cgltf.  Non trivial.

I'm a little pressed for time, so instead of doing the right thing and modifying gltfpack and cgltf, I'll write some script code to perform binary surgery on the json header inside each glb file and add these missing parameters.

Feel free to close this issue, or put it on ice, if you prefer.  I'll return to this at a later date, maybe when the spec is out of draft.

**Comment by zeux** [comment]
I'm going to close this for now because the timeline of completion and cgltf support for this extension is unclear to me; in general gltfpack process atm is to wait for any extension to get completed and then evaluate the cost of its support, and this happens whether an extension was mentioned in the issues or not generally, so we don't need to track this one in a special way.

Orthogonally - I agree that it would be nice if the extension didn't require extra per-primitive specification as that inflates the glTF payload for many-mesh scenes. It would also be easier to support the extension in a minimally viable format that way perhaps without cgltf changes.
