### ISSUE TITLE
gltfpack: Significant UV distortion for models with high tiling factors

### ISSUE THREAD

**Issue by donmccurdy** [zeux/meshoptimizer#93]
I think I'm seeing a similar issue in v0.13 of gltfpack. Testing against the model here: https://sketchfab.com/3d-models/melodia-city-hotel-a2fb8e4065ce470296d6d801daa37f18, with only default gltfpack options used:

| before | after |
|---|---|
|  ![before](https://user-images.githubusercontent.com/1848368/71429444-81e01280-267b-11ea-8513-7a20e5aaab85.png) | ![after](https://user-images.githubusercontent.com/1848368/71429445-83113f80-267b-11ea-96a3-019076cc0d07.png) |

annotated diff:

![diff](https://user-images.githubusercontent.com/1848368/71429490-b18f1a80-267b-11ea-89a5-df9ec7c0076e.png)

^Much of that diff is in reflections, which probably relates to merging meshes with transparency, and that seems fine. But the highlighted areas on the side of the building and the palm trees in front of the building show noticeable UV shifts that might suggest an issue:

![Screen Shot 2019-12-24 at 2 02 23 PM](https://user-images.githubusercontent.com/1848368/71429871-adfc9300-267d-11ea-84ae-867731a92f79.png)

**Comment by zeux** [comment]
FWIW all of the issues here are due to UV errors - running gltfpack with `-vt 16` (using all 16 bits for texture coordinate storage) fixes the windows and almost fixes the trees, although there's still some UV distortion noticeable.

The major issue here is that right now gltfpack doesn't use a per-material / per-texture UV quantization grid, which is necessary to decouple quantization of tree textures vs quantization of other textures for buildings. Once that is fixed, more changes might be necessary to get decent quality with default settings - I'll take a look at all of this soon-ish.

**Comment by zeux** [comment]
The change that closes this makes the result substantially better. There is still some UV distortion on the walls with the default settings, however with more texture coordinate bits (`-vt`) the result is basically perfect.

There's some opportunity for further improvement to automatically increase the bit count when the UV range is too high and/or adjust the mesh to reduce the UV range, but this can probably be done separately since on this model the result seems satisfactory.

**Comment by donmccurdy** [comment]
Great, thank you!

**Comment by Mobeen-Invozone** [comment]
Hi. I am compressing a obj file to gltf using meshoptimizer and the results are great. But facing one issue is that I have lost all the UV information in the compressed model. I am using the following command to compression:
