### ISSUE TITLE
Stuggle building with CMake

### ISSUE THREAD

**Issue by felixmariotto** [zeux/meshoptimizer#98]
Hi,
I would like to use gltfpack to optimize animated meshes for a web game. The issue is... I'm a web dev and never used cmake, I don't quite understand what I'm supposed to do with it to use gltfpack. Your readme states : 

> On Windows (and other platforms), you can use CMake:
> 
> ```
> cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=ON
> cmake --build . --config Release --target gltfpack
> ```
I tried to install CMake but got not CLI, only a GUI, and I have not idea where I'm supposed to run these commands.
Could you lead me to some online resources explaining how to use CMake in this context please ?

**Comment by zeux** [comment]
Just curious, is there a reason you can’t use a binary? Check out the Releases page. I need to update README to mention that.

**Comment by zeux** [comment]
The binary builds from this page should work: https://github.com/zeux/meshoptimizer/releases/tag/v0.13

I'm going to update README to clarify this. If you still want to build gltfpack yourself, you could follow https://cmake.org/runningcmake/ instead of using the command-line if you're on Windows, and just set the BUILD_TOOLS to ON yourself - however it would require installing Visual Studio, which you probably don't have - so it seems like the easier route is to use pre-built binaries.

**Comment by felixmariotto** [comment]
Sorry for the delay... I'm in a rush and have to put this aside for some time..
Thanks a lot for this information, I will look into it.

**Comment by zeux** [comment]
No worries; I've added a note to README that should hopefully help in the future https://github.com/zeux/meshoptimizer/commit/88a0a3f755ee6e216d8b169c702db7f9c277af97

**Comment by zeux** [comment]
Just to close the loop on this, I've reworked the README structure a bit so that gltfpack gets its own dedicated page, and uploaded an npm package which should hopefully reduce the friction :) https://www.npmjs.com/package/gltfpack

**Comment by felixmariotto** [comment]
Thank you, that's awesome !
